// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/github/aeonlucid/pogoprotos/networking/Platform.proto

package com.github.aeonlucid.pogoprotos.networking;

public final class Platform {
  private Platform() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code com.github.aeonlucid.pogoprotos.networking.platform.PlatformRequestType}
   */
  public enum PlatformRequestType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>METHOD_UNSET = 0;</code>
     */
    METHOD_UNSET(0),
    /**
     * <code>BUY_ITEM_POKECOINS = 2;</code>
     */
    BUY_ITEM_POKECOINS(2),
    /**
     * <code>BUY_ITEM_ANDROID = 3;</code>
     */
    BUY_ITEM_ANDROID(3),
    /**
     * <code>BUY_ITEM_IOS = 4;</code>
     */
    BUY_ITEM_IOS(4),
    /**
     * <code>GET_STORE_ITEMS = 5;</code>
     */
    GET_STORE_ITEMS(5),
    /**
     * <code>SEND_ENCRYPTED_SIGNATURE = 6;</code>
     */
    SEND_ENCRYPTED_SIGNATURE(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>METHOD_UNSET = 0;</code>
     */
    public static final int METHOD_UNSET_VALUE = 0;
    /**
     * <code>BUY_ITEM_POKECOINS = 2;</code>
     */
    public static final int BUY_ITEM_POKECOINS_VALUE = 2;
    /**
     * <code>BUY_ITEM_ANDROID = 3;</code>
     */
    public static final int BUY_ITEM_ANDROID_VALUE = 3;
    /**
     * <code>BUY_ITEM_IOS = 4;</code>
     */
    public static final int BUY_ITEM_IOS_VALUE = 4;
    /**
     * <code>GET_STORE_ITEMS = 5;</code>
     */
    public static final int GET_STORE_ITEMS_VALUE = 5;
    /**
     * <code>SEND_ENCRYPTED_SIGNATURE = 6;</code>
     */
    public static final int SEND_ENCRYPTED_SIGNATURE_VALUE = 6;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PlatformRequestType valueOf(int value) {
      return forNumber(value);
    }

    public static PlatformRequestType forNumber(int value) {
      switch (value) {
        case 0: return METHOD_UNSET;
        case 2: return BUY_ITEM_POKECOINS;
        case 3: return BUY_ITEM_ANDROID;
        case 4: return BUY_ITEM_IOS;
        case 5: return GET_STORE_ITEMS;
        case 6: return SEND_ENCRYPTED_SIGNATURE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PlatformRequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PlatformRequestType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PlatformRequestType>() {
            public PlatformRequestType findValueByNumber(int number) {
              return PlatformRequestType.forNumber(number);
            }
          };

    private final int value;

    private PlatformRequestType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.github.aeonlucid.pogoprotos.networking.platform.PlatformRequestType)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
