// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/github/aeonlucid/pogoprotos/settings/master/Pokemon.proto

package com.github.aeonlucid.pogoprotos.settings.master;

public final class Pokemon {
  private Pokemon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StatsAttributesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.aeonlucid.pogoprotos.settings.master.pokemon.StatsAttributes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 base_stamina = 1;</code>
     */
    int getBaseStamina();

    /**
     * <code>optional int32 base_attack = 2;</code>
     */
    int getBaseAttack();

    /**
     * <code>optional int32 base_defense = 3;</code>
     */
    int getBaseDefense();

    /**
     * <code>optional int32 dodge_energy_delta = 8;</code>
     */
    int getDodgeEnergyDelta();
  }
  /**
   * Protobuf type {@code com.github.aeonlucid.pogoprotos.settings.master.pokemon.StatsAttributes}
   */
  public  static final class StatsAttributes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.github.aeonlucid.pogoprotos.settings.master.pokemon.StatsAttributes)
      StatsAttributesOrBuilder {
    // Use StatsAttributes.newBuilder() to construct.
    private StatsAttributes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StatsAttributes() {
      baseStamina_ = 0;
      baseAttack_ = 0;
      baseDefense_ = 0;
      dodgeEnergyDelta_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private StatsAttributes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              baseStamina_ = input.readInt32();
              break;
            }
            case 16: {

              baseAttack_ = input.readInt32();
              break;
            }
            case 24: {

              baseDefense_ = input.readInt32();
              break;
            }
            case 64: {

              dodgeEnergyDelta_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.aeonlucid.pogoprotos.settings.master.Pokemon.internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_StatsAttributes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.aeonlucid.pogoprotos.settings.master.Pokemon.internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_StatsAttributes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes.class, com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes.Builder.class);
    }

    public static final int BASE_STAMINA_FIELD_NUMBER = 1;
    private int baseStamina_;
    /**
     * <code>optional int32 base_stamina = 1;</code>
     */
    public int getBaseStamina() {
      return baseStamina_;
    }

    public static final int BASE_ATTACK_FIELD_NUMBER = 2;
    private int baseAttack_;
    /**
     * <code>optional int32 base_attack = 2;</code>
     */
    public int getBaseAttack() {
      return baseAttack_;
    }

    public static final int BASE_DEFENSE_FIELD_NUMBER = 3;
    private int baseDefense_;
    /**
     * <code>optional int32 base_defense = 3;</code>
     */
    public int getBaseDefense() {
      return baseDefense_;
    }

    public static final int DODGE_ENERGY_DELTA_FIELD_NUMBER = 8;
    private int dodgeEnergyDelta_;
    /**
     * <code>optional int32 dodge_energy_delta = 8;</code>
     */
    public int getDodgeEnergyDelta() {
      return dodgeEnergyDelta_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (baseStamina_ != 0) {
        output.writeInt32(1, baseStamina_);
      }
      if (baseAttack_ != 0) {
        output.writeInt32(2, baseAttack_);
      }
      if (baseDefense_ != 0) {
        output.writeInt32(3, baseDefense_);
      }
      if (dodgeEnergyDelta_ != 0) {
        output.writeInt32(8, dodgeEnergyDelta_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (baseStamina_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, baseStamina_);
      }
      if (baseAttack_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, baseAttack_);
      }
      if (baseDefense_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, baseDefense_);
      }
      if (dodgeEnergyDelta_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, dodgeEnergyDelta_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes)) {
        return super.equals(obj);
      }
      com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes other = (com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes) obj;

      boolean result = true;
      result = result && (getBaseStamina()
          == other.getBaseStamina());
      result = result && (getBaseAttack()
          == other.getBaseAttack());
      result = result && (getBaseDefense()
          == other.getBaseDefense());
      result = result && (getDodgeEnergyDelta()
          == other.getDodgeEnergyDelta());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + BASE_STAMINA_FIELD_NUMBER;
      hash = (53 * hash) + getBaseStamina();
      hash = (37 * hash) + BASE_ATTACK_FIELD_NUMBER;
      hash = (53 * hash) + getBaseAttack();
      hash = (37 * hash) + BASE_DEFENSE_FIELD_NUMBER;
      hash = (53 * hash) + getBaseDefense();
      hash = (37 * hash) + DODGE_ENERGY_DELTA_FIELD_NUMBER;
      hash = (53 * hash) + getDodgeEnergyDelta();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.aeonlucid.pogoprotos.settings.master.pokemon.StatsAttributes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.aeonlucid.pogoprotos.settings.master.pokemon.StatsAttributes)
        com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.aeonlucid.pogoprotos.settings.master.Pokemon.internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_StatsAttributes_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.aeonlucid.pogoprotos.settings.master.Pokemon.internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_StatsAttributes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes.class, com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes.Builder.class);
      }

      // Construct using com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        baseStamina_ = 0;

        baseAttack_ = 0;

        baseDefense_ = 0;

        dodgeEnergyDelta_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.aeonlucid.pogoprotos.settings.master.Pokemon.internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_StatsAttributes_descriptor;
      }

      public com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes getDefaultInstanceForType() {
        return com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes.getDefaultInstance();
      }

      public com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes build() {
        com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes buildPartial() {
        com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes result = new com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes(this);
        result.baseStamina_ = baseStamina_;
        result.baseAttack_ = baseAttack_;
        result.baseDefense_ = baseDefense_;
        result.dodgeEnergyDelta_ = dodgeEnergyDelta_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes) {
          return mergeFrom((com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes other) {
        if (other == com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes.getDefaultInstance()) return this;
        if (other.getBaseStamina() != 0) {
          setBaseStamina(other.getBaseStamina());
        }
        if (other.getBaseAttack() != 0) {
          setBaseAttack(other.getBaseAttack());
        }
        if (other.getBaseDefense() != 0) {
          setBaseDefense(other.getBaseDefense());
        }
        if (other.getDodgeEnergyDelta() != 0) {
          setDodgeEnergyDelta(other.getDodgeEnergyDelta());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int baseStamina_ ;
      /**
       * <code>optional int32 base_stamina = 1;</code>
       */
      public int getBaseStamina() {
        return baseStamina_;
      }
      /**
       * <code>optional int32 base_stamina = 1;</code>
       */
      public Builder setBaseStamina(int value) {
        
        baseStamina_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 base_stamina = 1;</code>
       */
      public Builder clearBaseStamina() {
        
        baseStamina_ = 0;
        onChanged();
        return this;
      }

      private int baseAttack_ ;
      /**
       * <code>optional int32 base_attack = 2;</code>
       */
      public int getBaseAttack() {
        return baseAttack_;
      }
      /**
       * <code>optional int32 base_attack = 2;</code>
       */
      public Builder setBaseAttack(int value) {
        
        baseAttack_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 base_attack = 2;</code>
       */
      public Builder clearBaseAttack() {
        
        baseAttack_ = 0;
        onChanged();
        return this;
      }

      private int baseDefense_ ;
      /**
       * <code>optional int32 base_defense = 3;</code>
       */
      public int getBaseDefense() {
        return baseDefense_;
      }
      /**
       * <code>optional int32 base_defense = 3;</code>
       */
      public Builder setBaseDefense(int value) {
        
        baseDefense_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 base_defense = 3;</code>
       */
      public Builder clearBaseDefense() {
        
        baseDefense_ = 0;
        onChanged();
        return this;
      }

      private int dodgeEnergyDelta_ ;
      /**
       * <code>optional int32 dodge_energy_delta = 8;</code>
       */
      public int getDodgeEnergyDelta() {
        return dodgeEnergyDelta_;
      }
      /**
       * <code>optional int32 dodge_energy_delta = 8;</code>
       */
      public Builder setDodgeEnergyDelta(int value) {
        
        dodgeEnergyDelta_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 dodge_energy_delta = 8;</code>
       */
      public Builder clearDodgeEnergyDelta() {
        
        dodgeEnergyDelta_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.github.aeonlucid.pogoprotos.settings.master.pokemon.StatsAttributes)
    }

    // @@protoc_insertion_point(class_scope:com.github.aeonlucid.pogoprotos.settings.master.pokemon.StatsAttributes)
    private static final com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes();
    }

    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StatsAttributes>
        PARSER = new com.google.protobuf.AbstractParser<StatsAttributes>() {
      public StatsAttributes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new StatsAttributes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StatsAttributes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StatsAttributes> getParserForType() {
      return PARSER;
    }

    public com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CameraAttributesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.aeonlucid.pogoprotos.settings.master.pokemon.CameraAttributes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional float disk_radius_m = 1;</code>
     */
    float getDiskRadiusM();

    /**
     * <code>optional float cylinder_radius_m = 2;</code>
     */
    float getCylinderRadiusM();

    /**
     * <code>optional float cylinder_height_m = 3;</code>
     */
    float getCylinderHeightM();

    /**
     * <code>optional float cylinder_ground_m = 4;</code>
     */
    float getCylinderGroundM();

    /**
     * <code>optional float shoulder_mode_scale = 5;</code>
     */
    float getShoulderModeScale();
  }
  /**
   * Protobuf type {@code com.github.aeonlucid.pogoprotos.settings.master.pokemon.CameraAttributes}
   */
  public  static final class CameraAttributes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.github.aeonlucid.pogoprotos.settings.master.pokemon.CameraAttributes)
      CameraAttributesOrBuilder {
    // Use CameraAttributes.newBuilder() to construct.
    private CameraAttributes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CameraAttributes() {
      diskRadiusM_ = 0F;
      cylinderRadiusM_ = 0F;
      cylinderHeightM_ = 0F;
      cylinderGroundM_ = 0F;
      shoulderModeScale_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CameraAttributes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 13: {

              diskRadiusM_ = input.readFloat();
              break;
            }
            case 21: {

              cylinderRadiusM_ = input.readFloat();
              break;
            }
            case 29: {

              cylinderHeightM_ = input.readFloat();
              break;
            }
            case 37: {

              cylinderGroundM_ = input.readFloat();
              break;
            }
            case 45: {

              shoulderModeScale_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.aeonlucid.pogoprotos.settings.master.Pokemon.internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_CameraAttributes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.aeonlucid.pogoprotos.settings.master.Pokemon.internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_CameraAttributes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes.class, com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes.Builder.class);
    }

    public static final int DISK_RADIUS_M_FIELD_NUMBER = 1;
    private float diskRadiusM_;
    /**
     * <code>optional float disk_radius_m = 1;</code>
     */
    public float getDiskRadiusM() {
      return diskRadiusM_;
    }

    public static final int CYLINDER_RADIUS_M_FIELD_NUMBER = 2;
    private float cylinderRadiusM_;
    /**
     * <code>optional float cylinder_radius_m = 2;</code>
     */
    public float getCylinderRadiusM() {
      return cylinderRadiusM_;
    }

    public static final int CYLINDER_HEIGHT_M_FIELD_NUMBER = 3;
    private float cylinderHeightM_;
    /**
     * <code>optional float cylinder_height_m = 3;</code>
     */
    public float getCylinderHeightM() {
      return cylinderHeightM_;
    }

    public static final int CYLINDER_GROUND_M_FIELD_NUMBER = 4;
    private float cylinderGroundM_;
    /**
     * <code>optional float cylinder_ground_m = 4;</code>
     */
    public float getCylinderGroundM() {
      return cylinderGroundM_;
    }

    public static final int SHOULDER_MODE_SCALE_FIELD_NUMBER = 5;
    private float shoulderModeScale_;
    /**
     * <code>optional float shoulder_mode_scale = 5;</code>
     */
    public float getShoulderModeScale() {
      return shoulderModeScale_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (diskRadiusM_ != 0F) {
        output.writeFloat(1, diskRadiusM_);
      }
      if (cylinderRadiusM_ != 0F) {
        output.writeFloat(2, cylinderRadiusM_);
      }
      if (cylinderHeightM_ != 0F) {
        output.writeFloat(3, cylinderHeightM_);
      }
      if (cylinderGroundM_ != 0F) {
        output.writeFloat(4, cylinderGroundM_);
      }
      if (shoulderModeScale_ != 0F) {
        output.writeFloat(5, shoulderModeScale_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (diskRadiusM_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, diskRadiusM_);
      }
      if (cylinderRadiusM_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, cylinderRadiusM_);
      }
      if (cylinderHeightM_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, cylinderHeightM_);
      }
      if (cylinderGroundM_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, cylinderGroundM_);
      }
      if (shoulderModeScale_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, shoulderModeScale_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes)) {
        return super.equals(obj);
      }
      com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes other = (com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes) obj;

      boolean result = true;
      result = result && (
          java.lang.Float.floatToIntBits(getDiskRadiusM())
          == java.lang.Float.floatToIntBits(
              other.getDiskRadiusM()));
      result = result && (
          java.lang.Float.floatToIntBits(getCylinderRadiusM())
          == java.lang.Float.floatToIntBits(
              other.getCylinderRadiusM()));
      result = result && (
          java.lang.Float.floatToIntBits(getCylinderHeightM())
          == java.lang.Float.floatToIntBits(
              other.getCylinderHeightM()));
      result = result && (
          java.lang.Float.floatToIntBits(getCylinderGroundM())
          == java.lang.Float.floatToIntBits(
              other.getCylinderGroundM()));
      result = result && (
          java.lang.Float.floatToIntBits(getShoulderModeScale())
          == java.lang.Float.floatToIntBits(
              other.getShoulderModeScale()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + DISK_RADIUS_M_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getDiskRadiusM());
      hash = (37 * hash) + CYLINDER_RADIUS_M_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getCylinderRadiusM());
      hash = (37 * hash) + CYLINDER_HEIGHT_M_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getCylinderHeightM());
      hash = (37 * hash) + CYLINDER_GROUND_M_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getCylinderGroundM());
      hash = (37 * hash) + SHOULDER_MODE_SCALE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getShoulderModeScale());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.aeonlucid.pogoprotos.settings.master.pokemon.CameraAttributes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.aeonlucid.pogoprotos.settings.master.pokemon.CameraAttributes)
        com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.aeonlucid.pogoprotos.settings.master.Pokemon.internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_CameraAttributes_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.aeonlucid.pogoprotos.settings.master.Pokemon.internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_CameraAttributes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes.class, com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes.Builder.class);
      }

      // Construct using com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        diskRadiusM_ = 0F;

        cylinderRadiusM_ = 0F;

        cylinderHeightM_ = 0F;

        cylinderGroundM_ = 0F;

        shoulderModeScale_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.aeonlucid.pogoprotos.settings.master.Pokemon.internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_CameraAttributes_descriptor;
      }

      public com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes getDefaultInstanceForType() {
        return com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes.getDefaultInstance();
      }

      public com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes build() {
        com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes buildPartial() {
        com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes result = new com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes(this);
        result.diskRadiusM_ = diskRadiusM_;
        result.cylinderRadiusM_ = cylinderRadiusM_;
        result.cylinderHeightM_ = cylinderHeightM_;
        result.cylinderGroundM_ = cylinderGroundM_;
        result.shoulderModeScale_ = shoulderModeScale_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes) {
          return mergeFrom((com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes other) {
        if (other == com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes.getDefaultInstance()) return this;
        if (other.getDiskRadiusM() != 0F) {
          setDiskRadiusM(other.getDiskRadiusM());
        }
        if (other.getCylinderRadiusM() != 0F) {
          setCylinderRadiusM(other.getCylinderRadiusM());
        }
        if (other.getCylinderHeightM() != 0F) {
          setCylinderHeightM(other.getCylinderHeightM());
        }
        if (other.getCylinderGroundM() != 0F) {
          setCylinderGroundM(other.getCylinderGroundM());
        }
        if (other.getShoulderModeScale() != 0F) {
          setShoulderModeScale(other.getShoulderModeScale());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float diskRadiusM_ ;
      /**
       * <code>optional float disk_radius_m = 1;</code>
       */
      public float getDiskRadiusM() {
        return diskRadiusM_;
      }
      /**
       * <code>optional float disk_radius_m = 1;</code>
       */
      public Builder setDiskRadiusM(float value) {
        
        diskRadiusM_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float disk_radius_m = 1;</code>
       */
      public Builder clearDiskRadiusM() {
        
        diskRadiusM_ = 0F;
        onChanged();
        return this;
      }

      private float cylinderRadiusM_ ;
      /**
       * <code>optional float cylinder_radius_m = 2;</code>
       */
      public float getCylinderRadiusM() {
        return cylinderRadiusM_;
      }
      /**
       * <code>optional float cylinder_radius_m = 2;</code>
       */
      public Builder setCylinderRadiusM(float value) {
        
        cylinderRadiusM_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float cylinder_radius_m = 2;</code>
       */
      public Builder clearCylinderRadiusM() {
        
        cylinderRadiusM_ = 0F;
        onChanged();
        return this;
      }

      private float cylinderHeightM_ ;
      /**
       * <code>optional float cylinder_height_m = 3;</code>
       */
      public float getCylinderHeightM() {
        return cylinderHeightM_;
      }
      /**
       * <code>optional float cylinder_height_m = 3;</code>
       */
      public Builder setCylinderHeightM(float value) {
        
        cylinderHeightM_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float cylinder_height_m = 3;</code>
       */
      public Builder clearCylinderHeightM() {
        
        cylinderHeightM_ = 0F;
        onChanged();
        return this;
      }

      private float cylinderGroundM_ ;
      /**
       * <code>optional float cylinder_ground_m = 4;</code>
       */
      public float getCylinderGroundM() {
        return cylinderGroundM_;
      }
      /**
       * <code>optional float cylinder_ground_m = 4;</code>
       */
      public Builder setCylinderGroundM(float value) {
        
        cylinderGroundM_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float cylinder_ground_m = 4;</code>
       */
      public Builder clearCylinderGroundM() {
        
        cylinderGroundM_ = 0F;
        onChanged();
        return this;
      }

      private float shoulderModeScale_ ;
      /**
       * <code>optional float shoulder_mode_scale = 5;</code>
       */
      public float getShoulderModeScale() {
        return shoulderModeScale_;
      }
      /**
       * <code>optional float shoulder_mode_scale = 5;</code>
       */
      public Builder setShoulderModeScale(float value) {
        
        shoulderModeScale_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float shoulder_mode_scale = 5;</code>
       */
      public Builder clearShoulderModeScale() {
        
        shoulderModeScale_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.github.aeonlucid.pogoprotos.settings.master.pokemon.CameraAttributes)
    }

    // @@protoc_insertion_point(class_scope:com.github.aeonlucid.pogoprotos.settings.master.pokemon.CameraAttributes)
    private static final com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes();
    }

    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CameraAttributes>
        PARSER = new com.google.protobuf.AbstractParser<CameraAttributes>() {
      public CameraAttributes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CameraAttributes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CameraAttributes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CameraAttributes> getParserForType() {
      return PARSER;
    }

    public com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EncounterAttributesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.aeonlucid.pogoprotos.settings.master.pokemon.EncounterAttributes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional float base_capture_rate = 1;</code>
     */
    float getBaseCaptureRate();

    /**
     * <code>optional float base_flee_rate = 2;</code>
     */
    float getBaseFleeRate();

    /**
     * <code>optional float collision_radius_m = 3;</code>
     */
    float getCollisionRadiusM();

    /**
     * <code>optional float collision_height_m = 4;</code>
     */
    float getCollisionHeightM();

    /**
     * <code>optional float collision_head_radius_m = 5;</code>
     */
    float getCollisionHeadRadiusM();

    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonMovementType movement_type = 6;</code>
     */
    int getMovementTypeValue();
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonMovementType movement_type = 6;</code>
     */
    com.github.aeonlucid.pogoprotos.Enums.PokemonMovementType getMovementType();

    /**
     * <code>optional float movement_timer_s = 7;</code>
     */
    float getMovementTimerS();

    /**
     * <code>optional float jump_time_s = 8;</code>
     */
    float getJumpTimeS();

    /**
     * <code>optional float attack_timer_s = 9;</code>
     */
    float getAttackTimerS();
  }
  /**
   * Protobuf type {@code com.github.aeonlucid.pogoprotos.settings.master.pokemon.EncounterAttributes}
   */
  public  static final class EncounterAttributes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.github.aeonlucid.pogoprotos.settings.master.pokemon.EncounterAttributes)
      EncounterAttributesOrBuilder {
    // Use EncounterAttributes.newBuilder() to construct.
    private EncounterAttributes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EncounterAttributes() {
      baseCaptureRate_ = 0F;
      baseFleeRate_ = 0F;
      collisionRadiusM_ = 0F;
      collisionHeightM_ = 0F;
      collisionHeadRadiusM_ = 0F;
      movementType_ = 0;
      movementTimerS_ = 0F;
      jumpTimeS_ = 0F;
      attackTimerS_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private EncounterAttributes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 13: {

              baseCaptureRate_ = input.readFloat();
              break;
            }
            case 21: {

              baseFleeRate_ = input.readFloat();
              break;
            }
            case 29: {

              collisionRadiusM_ = input.readFloat();
              break;
            }
            case 37: {

              collisionHeightM_ = input.readFloat();
              break;
            }
            case 45: {

              collisionHeadRadiusM_ = input.readFloat();
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              movementType_ = rawValue;
              break;
            }
            case 61: {

              movementTimerS_ = input.readFloat();
              break;
            }
            case 69: {

              jumpTimeS_ = input.readFloat();
              break;
            }
            case 77: {

              attackTimerS_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.aeonlucid.pogoprotos.settings.master.Pokemon.internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_EncounterAttributes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.aeonlucid.pogoprotos.settings.master.Pokemon.internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_EncounterAttributes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes.class, com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes.Builder.class);
    }

    public static final int BASE_CAPTURE_RATE_FIELD_NUMBER = 1;
    private float baseCaptureRate_;
    /**
     * <code>optional float base_capture_rate = 1;</code>
     */
    public float getBaseCaptureRate() {
      return baseCaptureRate_;
    }

    public static final int BASE_FLEE_RATE_FIELD_NUMBER = 2;
    private float baseFleeRate_;
    /**
     * <code>optional float base_flee_rate = 2;</code>
     */
    public float getBaseFleeRate() {
      return baseFleeRate_;
    }

    public static final int COLLISION_RADIUS_M_FIELD_NUMBER = 3;
    private float collisionRadiusM_;
    /**
     * <code>optional float collision_radius_m = 3;</code>
     */
    public float getCollisionRadiusM() {
      return collisionRadiusM_;
    }

    public static final int COLLISION_HEIGHT_M_FIELD_NUMBER = 4;
    private float collisionHeightM_;
    /**
     * <code>optional float collision_height_m = 4;</code>
     */
    public float getCollisionHeightM() {
      return collisionHeightM_;
    }

    public static final int COLLISION_HEAD_RADIUS_M_FIELD_NUMBER = 5;
    private float collisionHeadRadiusM_;
    /**
     * <code>optional float collision_head_radius_m = 5;</code>
     */
    public float getCollisionHeadRadiusM() {
      return collisionHeadRadiusM_;
    }

    public static final int MOVEMENT_TYPE_FIELD_NUMBER = 6;
    private int movementType_;
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonMovementType movement_type = 6;</code>
     */
    public int getMovementTypeValue() {
      return movementType_;
    }
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonMovementType movement_type = 6;</code>
     */
    public com.github.aeonlucid.pogoprotos.Enums.PokemonMovementType getMovementType() {
      com.github.aeonlucid.pogoprotos.Enums.PokemonMovementType result = com.github.aeonlucid.pogoprotos.Enums.PokemonMovementType.valueOf(movementType_);
      return result == null ? com.github.aeonlucid.pogoprotos.Enums.PokemonMovementType.UNRECOGNIZED : result;
    }

    public static final int MOVEMENT_TIMER_S_FIELD_NUMBER = 7;
    private float movementTimerS_;
    /**
     * <code>optional float movement_timer_s = 7;</code>
     */
    public float getMovementTimerS() {
      return movementTimerS_;
    }

    public static final int JUMP_TIME_S_FIELD_NUMBER = 8;
    private float jumpTimeS_;
    /**
     * <code>optional float jump_time_s = 8;</code>
     */
    public float getJumpTimeS() {
      return jumpTimeS_;
    }

    public static final int ATTACK_TIMER_S_FIELD_NUMBER = 9;
    private float attackTimerS_;
    /**
     * <code>optional float attack_timer_s = 9;</code>
     */
    public float getAttackTimerS() {
      return attackTimerS_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (baseCaptureRate_ != 0F) {
        output.writeFloat(1, baseCaptureRate_);
      }
      if (baseFleeRate_ != 0F) {
        output.writeFloat(2, baseFleeRate_);
      }
      if (collisionRadiusM_ != 0F) {
        output.writeFloat(3, collisionRadiusM_);
      }
      if (collisionHeightM_ != 0F) {
        output.writeFloat(4, collisionHeightM_);
      }
      if (collisionHeadRadiusM_ != 0F) {
        output.writeFloat(5, collisionHeadRadiusM_);
      }
      if (movementType_ != com.github.aeonlucid.pogoprotos.Enums.PokemonMovementType.MOVEMENT_STATIC.getNumber()) {
        output.writeEnum(6, movementType_);
      }
      if (movementTimerS_ != 0F) {
        output.writeFloat(7, movementTimerS_);
      }
      if (jumpTimeS_ != 0F) {
        output.writeFloat(8, jumpTimeS_);
      }
      if (attackTimerS_ != 0F) {
        output.writeFloat(9, attackTimerS_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (baseCaptureRate_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, baseCaptureRate_);
      }
      if (baseFleeRate_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, baseFleeRate_);
      }
      if (collisionRadiusM_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, collisionRadiusM_);
      }
      if (collisionHeightM_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, collisionHeightM_);
      }
      if (collisionHeadRadiusM_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, collisionHeadRadiusM_);
      }
      if (movementType_ != com.github.aeonlucid.pogoprotos.Enums.PokemonMovementType.MOVEMENT_STATIC.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, movementType_);
      }
      if (movementTimerS_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, movementTimerS_);
      }
      if (jumpTimeS_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, jumpTimeS_);
      }
      if (attackTimerS_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(9, attackTimerS_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes)) {
        return super.equals(obj);
      }
      com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes other = (com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes) obj;

      boolean result = true;
      result = result && (
          java.lang.Float.floatToIntBits(getBaseCaptureRate())
          == java.lang.Float.floatToIntBits(
              other.getBaseCaptureRate()));
      result = result && (
          java.lang.Float.floatToIntBits(getBaseFleeRate())
          == java.lang.Float.floatToIntBits(
              other.getBaseFleeRate()));
      result = result && (
          java.lang.Float.floatToIntBits(getCollisionRadiusM())
          == java.lang.Float.floatToIntBits(
              other.getCollisionRadiusM()));
      result = result && (
          java.lang.Float.floatToIntBits(getCollisionHeightM())
          == java.lang.Float.floatToIntBits(
              other.getCollisionHeightM()));
      result = result && (
          java.lang.Float.floatToIntBits(getCollisionHeadRadiusM())
          == java.lang.Float.floatToIntBits(
              other.getCollisionHeadRadiusM()));
      result = result && movementType_ == other.movementType_;
      result = result && (
          java.lang.Float.floatToIntBits(getMovementTimerS())
          == java.lang.Float.floatToIntBits(
              other.getMovementTimerS()));
      result = result && (
          java.lang.Float.floatToIntBits(getJumpTimeS())
          == java.lang.Float.floatToIntBits(
              other.getJumpTimeS()));
      result = result && (
          java.lang.Float.floatToIntBits(getAttackTimerS())
          == java.lang.Float.floatToIntBits(
              other.getAttackTimerS()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + BASE_CAPTURE_RATE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getBaseCaptureRate());
      hash = (37 * hash) + BASE_FLEE_RATE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getBaseFleeRate());
      hash = (37 * hash) + COLLISION_RADIUS_M_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getCollisionRadiusM());
      hash = (37 * hash) + COLLISION_HEIGHT_M_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getCollisionHeightM());
      hash = (37 * hash) + COLLISION_HEAD_RADIUS_M_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getCollisionHeadRadiusM());
      hash = (37 * hash) + MOVEMENT_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + movementType_;
      hash = (37 * hash) + MOVEMENT_TIMER_S_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getMovementTimerS());
      hash = (37 * hash) + JUMP_TIME_S_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getJumpTimeS());
      hash = (37 * hash) + ATTACK_TIMER_S_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAttackTimerS());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.aeonlucid.pogoprotos.settings.master.pokemon.EncounterAttributes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.aeonlucid.pogoprotos.settings.master.pokemon.EncounterAttributes)
        com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.aeonlucid.pogoprotos.settings.master.Pokemon.internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_EncounterAttributes_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.aeonlucid.pogoprotos.settings.master.Pokemon.internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_EncounterAttributes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes.class, com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes.Builder.class);
      }

      // Construct using com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        baseCaptureRate_ = 0F;

        baseFleeRate_ = 0F;

        collisionRadiusM_ = 0F;

        collisionHeightM_ = 0F;

        collisionHeadRadiusM_ = 0F;

        movementType_ = 0;

        movementTimerS_ = 0F;

        jumpTimeS_ = 0F;

        attackTimerS_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.aeonlucid.pogoprotos.settings.master.Pokemon.internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_EncounterAttributes_descriptor;
      }

      public com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes getDefaultInstanceForType() {
        return com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes.getDefaultInstance();
      }

      public com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes build() {
        com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes buildPartial() {
        com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes result = new com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes(this);
        result.baseCaptureRate_ = baseCaptureRate_;
        result.baseFleeRate_ = baseFleeRate_;
        result.collisionRadiusM_ = collisionRadiusM_;
        result.collisionHeightM_ = collisionHeightM_;
        result.collisionHeadRadiusM_ = collisionHeadRadiusM_;
        result.movementType_ = movementType_;
        result.movementTimerS_ = movementTimerS_;
        result.jumpTimeS_ = jumpTimeS_;
        result.attackTimerS_ = attackTimerS_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes) {
          return mergeFrom((com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes other) {
        if (other == com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes.getDefaultInstance()) return this;
        if (other.getBaseCaptureRate() != 0F) {
          setBaseCaptureRate(other.getBaseCaptureRate());
        }
        if (other.getBaseFleeRate() != 0F) {
          setBaseFleeRate(other.getBaseFleeRate());
        }
        if (other.getCollisionRadiusM() != 0F) {
          setCollisionRadiusM(other.getCollisionRadiusM());
        }
        if (other.getCollisionHeightM() != 0F) {
          setCollisionHeightM(other.getCollisionHeightM());
        }
        if (other.getCollisionHeadRadiusM() != 0F) {
          setCollisionHeadRadiusM(other.getCollisionHeadRadiusM());
        }
        if (other.movementType_ != 0) {
          setMovementTypeValue(other.getMovementTypeValue());
        }
        if (other.getMovementTimerS() != 0F) {
          setMovementTimerS(other.getMovementTimerS());
        }
        if (other.getJumpTimeS() != 0F) {
          setJumpTimeS(other.getJumpTimeS());
        }
        if (other.getAttackTimerS() != 0F) {
          setAttackTimerS(other.getAttackTimerS());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float baseCaptureRate_ ;
      /**
       * <code>optional float base_capture_rate = 1;</code>
       */
      public float getBaseCaptureRate() {
        return baseCaptureRate_;
      }
      /**
       * <code>optional float base_capture_rate = 1;</code>
       */
      public Builder setBaseCaptureRate(float value) {
        
        baseCaptureRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float base_capture_rate = 1;</code>
       */
      public Builder clearBaseCaptureRate() {
        
        baseCaptureRate_ = 0F;
        onChanged();
        return this;
      }

      private float baseFleeRate_ ;
      /**
       * <code>optional float base_flee_rate = 2;</code>
       */
      public float getBaseFleeRate() {
        return baseFleeRate_;
      }
      /**
       * <code>optional float base_flee_rate = 2;</code>
       */
      public Builder setBaseFleeRate(float value) {
        
        baseFleeRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float base_flee_rate = 2;</code>
       */
      public Builder clearBaseFleeRate() {
        
        baseFleeRate_ = 0F;
        onChanged();
        return this;
      }

      private float collisionRadiusM_ ;
      /**
       * <code>optional float collision_radius_m = 3;</code>
       */
      public float getCollisionRadiusM() {
        return collisionRadiusM_;
      }
      /**
       * <code>optional float collision_radius_m = 3;</code>
       */
      public Builder setCollisionRadiusM(float value) {
        
        collisionRadiusM_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float collision_radius_m = 3;</code>
       */
      public Builder clearCollisionRadiusM() {
        
        collisionRadiusM_ = 0F;
        onChanged();
        return this;
      }

      private float collisionHeightM_ ;
      /**
       * <code>optional float collision_height_m = 4;</code>
       */
      public float getCollisionHeightM() {
        return collisionHeightM_;
      }
      /**
       * <code>optional float collision_height_m = 4;</code>
       */
      public Builder setCollisionHeightM(float value) {
        
        collisionHeightM_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float collision_height_m = 4;</code>
       */
      public Builder clearCollisionHeightM() {
        
        collisionHeightM_ = 0F;
        onChanged();
        return this;
      }

      private float collisionHeadRadiusM_ ;
      /**
       * <code>optional float collision_head_radius_m = 5;</code>
       */
      public float getCollisionHeadRadiusM() {
        return collisionHeadRadiusM_;
      }
      /**
       * <code>optional float collision_head_radius_m = 5;</code>
       */
      public Builder setCollisionHeadRadiusM(float value) {
        
        collisionHeadRadiusM_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float collision_head_radius_m = 5;</code>
       */
      public Builder clearCollisionHeadRadiusM() {
        
        collisionHeadRadiusM_ = 0F;
        onChanged();
        return this;
      }

      private int movementType_ = 0;
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonMovementType movement_type = 6;</code>
       */
      public int getMovementTypeValue() {
        return movementType_;
      }
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonMovementType movement_type = 6;</code>
       */
      public Builder setMovementTypeValue(int value) {
        movementType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonMovementType movement_type = 6;</code>
       */
      public com.github.aeonlucid.pogoprotos.Enums.PokemonMovementType getMovementType() {
        com.github.aeonlucid.pogoprotos.Enums.PokemonMovementType result = com.github.aeonlucid.pogoprotos.Enums.PokemonMovementType.valueOf(movementType_);
        return result == null ? com.github.aeonlucid.pogoprotos.Enums.PokemonMovementType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonMovementType movement_type = 6;</code>
       */
      public Builder setMovementType(com.github.aeonlucid.pogoprotos.Enums.PokemonMovementType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        movementType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonMovementType movement_type = 6;</code>
       */
      public Builder clearMovementType() {
        
        movementType_ = 0;
        onChanged();
        return this;
      }

      private float movementTimerS_ ;
      /**
       * <code>optional float movement_timer_s = 7;</code>
       */
      public float getMovementTimerS() {
        return movementTimerS_;
      }
      /**
       * <code>optional float movement_timer_s = 7;</code>
       */
      public Builder setMovementTimerS(float value) {
        
        movementTimerS_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float movement_timer_s = 7;</code>
       */
      public Builder clearMovementTimerS() {
        
        movementTimerS_ = 0F;
        onChanged();
        return this;
      }

      private float jumpTimeS_ ;
      /**
       * <code>optional float jump_time_s = 8;</code>
       */
      public float getJumpTimeS() {
        return jumpTimeS_;
      }
      /**
       * <code>optional float jump_time_s = 8;</code>
       */
      public Builder setJumpTimeS(float value) {
        
        jumpTimeS_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float jump_time_s = 8;</code>
       */
      public Builder clearJumpTimeS() {
        
        jumpTimeS_ = 0F;
        onChanged();
        return this;
      }

      private float attackTimerS_ ;
      /**
       * <code>optional float attack_timer_s = 9;</code>
       */
      public float getAttackTimerS() {
        return attackTimerS_;
      }
      /**
       * <code>optional float attack_timer_s = 9;</code>
       */
      public Builder setAttackTimerS(float value) {
        
        attackTimerS_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float attack_timer_s = 9;</code>
       */
      public Builder clearAttackTimerS() {
        
        attackTimerS_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.github.aeonlucid.pogoprotos.settings.master.pokemon.EncounterAttributes)
    }

    // @@protoc_insertion_point(class_scope:com.github.aeonlucid.pogoprotos.settings.master.pokemon.EncounterAttributes)
    private static final com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes();
    }

    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EncounterAttributes>
        PARSER = new com.google.protobuf.AbstractParser<EncounterAttributes>() {
      public EncounterAttributes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new EncounterAttributes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EncounterAttributes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EncounterAttributes> getParserForType() {
      return PARSER;
    }

    public com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_StatsAttributes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_StatsAttributes_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_CameraAttributes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_CameraAttributes_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_EncounterAttributes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_EncounterAttributes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n=com/github/aeonlucid/pogoprotos/settin" +
      "gs/master/Pokemon.proto\0227com.github.aeon" +
      "lucid.pogoprotos.settings.master.pokemon" +
      "\032+com/github/aeonlucid/pogoprotos/Enums." +
      "proto\"n\n\017StatsAttributes\022\024\n\014base_stamina" +
      "\030\001 \001(\005\022\023\n\013base_attack\030\002 \001(\005\022\024\n\014base_defe" +
      "nse\030\003 \001(\005\022\032\n\022dodge_energy_delta\030\010 \001(\005\"\227\001" +
      "\n\020CameraAttributes\022\025\n\rdisk_radius_m\030\001 \001(" +
      "\002\022\031\n\021cylinder_radius_m\030\002 \001(\002\022\031\n\021cylinder" +
      "_height_m\030\003 \001(\002\022\031\n\021cylinder_ground_m\030\004 \001",
      "(\002\022\033\n\023shoulder_mode_scale\030\005 \001(\002\"\273\002\n\023Enco" +
      "unterAttributes\022\031\n\021base_capture_rate\030\001 \001" +
      "(\002\022\026\n\016base_flee_rate\030\002 \001(\002\022\032\n\022collision_" +
      "radius_m\030\003 \001(\002\022\032\n\022collision_height_m\030\004 \001" +
      "(\002\022\037\n\027collision_head_radius_m\030\005 \001(\002\022Q\n\rm" +
      "ovement_type\030\006 \001(\0162:.com.github.aeonluci" +
      "d.pogoprotos.enums.PokemonMovementType\022\030" +
      "\n\020movement_timer_s\030\007 \001(\002\022\023\n\013jump_time_s\030" +
      "\010 \001(\002\022\026\n\016attack_timer_s\030\t \001(\002B:\n/com.git" +
      "hub.aeonlucid.pogoprotos.settings.master",
      "B\007Pokemonb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.aeonlucid.pogoprotos.Enums.getDescriptor(),
        }, assigner);
    internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_StatsAttributes_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_StatsAttributes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_StatsAttributes_descriptor,
        new java.lang.String[] { "BaseStamina", "BaseAttack", "BaseDefense", "DodgeEnergyDelta", });
    internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_CameraAttributes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_CameraAttributes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_CameraAttributes_descriptor,
        new java.lang.String[] { "DiskRadiusM", "CylinderRadiusM", "CylinderHeightM", "CylinderGroundM", "ShoulderModeScale", });
    internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_EncounterAttributes_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_EncounterAttributes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_aeonlucid_pogoprotos_settings_master_pokemon_EncounterAttributes_descriptor,
        new java.lang.String[] { "BaseCaptureRate", "BaseFleeRate", "CollisionRadiusM", "CollisionHeightM", "CollisionHeadRadiusM", "MovementType", "MovementTimerS", "JumpTimeS", "AttackTimerS", });
    com.github.aeonlucid.pogoprotos.Enums.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
