// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/github/aeonlucid/pogoprotos/settings/master/Pokemon.proto

package com.github.aeonlucid.pogoprotos.settings.master;

public final class Pokemon {
  private Pokemon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface EncounterAttributesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.aeonlucid.pogoprotos.settings.master.pokemon.EncounterAttributes)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional float base_capture_rate = 1;</code>
     */
    float getBaseCaptureRate();

    /**
     * <code>optional float base_flee_rate = 2;</code>
     */
    float getBaseFleeRate();

    /**
     * <code>optional float collision_radius_m = 3;</code>
     */
    float getCollisionRadiusM();

    /**
     * <code>optional float collision_height_m = 4;</code>
     */
    float getCollisionHeightM();

    /**
     * <code>optional float collision_head_radius_m = 5;</code>
     */
    float getCollisionHeadRadiusM();

    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonMovementType movement_type = 6;</code>
     */
    int getMovementTypeValue();
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonMovementType movement_type = 6;</code>
     */
    com.github.aeonlucid.pogoprotos.Enums.PokemonMovementType getMovementType();

    /**
     * <code>optional float movement_timer_s = 7;</code>
     */
    float getMovementTimerS();

    /**
     * <code>optional float jump_time_s = 8;</code>
     */
    float getJumpTimeS();

    /**
     * <code>optional float attack_timer_s = 9;</code>
     */
    float getAttackTimerS();
  }
  /**
   * Protobuf type {@code com.github.aeonlucid.pogoprotos.settings.master.pokemon.EncounterAttributes}
   */
  public  static final class EncounterAttributes extends
      com.google.protobuf.GeneratedMessageLite<
          EncounterAttributes, EncounterAttributes.Builder> implements
      // @@protoc_insertion_point(message_implements:com.github.aeonlucid.pogoprotos.settings.master.pokemon.EncounterAttributes)
      EncounterAttributesOrBuilder {
    private EncounterAttributes() {
    }
    public static final int BASE_CAPTURE_RATE_FIELD_NUMBER = 1;
    private float baseCaptureRate_;
    /**
     * <code>optional float base_capture_rate = 1;</code>
     */
    public float getBaseCaptureRate() {
      return baseCaptureRate_;
    }
    /**
     * <code>optional float base_capture_rate = 1;</code>
     */
    private void setBaseCaptureRate(float value) {
      
      baseCaptureRate_ = value;
    }
    /**
     * <code>optional float base_capture_rate = 1;</code>
     */
    private void clearBaseCaptureRate() {
      
      baseCaptureRate_ = 0F;
    }

    public static final int BASE_FLEE_RATE_FIELD_NUMBER = 2;
    private float baseFleeRate_;
    /**
     * <code>optional float base_flee_rate = 2;</code>
     */
    public float getBaseFleeRate() {
      return baseFleeRate_;
    }
    /**
     * <code>optional float base_flee_rate = 2;</code>
     */
    private void setBaseFleeRate(float value) {
      
      baseFleeRate_ = value;
    }
    /**
     * <code>optional float base_flee_rate = 2;</code>
     */
    private void clearBaseFleeRate() {
      
      baseFleeRate_ = 0F;
    }

    public static final int COLLISION_RADIUS_M_FIELD_NUMBER = 3;
    private float collisionRadiusM_;
    /**
     * <code>optional float collision_radius_m = 3;</code>
     */
    public float getCollisionRadiusM() {
      return collisionRadiusM_;
    }
    /**
     * <code>optional float collision_radius_m = 3;</code>
     */
    private void setCollisionRadiusM(float value) {
      
      collisionRadiusM_ = value;
    }
    /**
     * <code>optional float collision_radius_m = 3;</code>
     */
    private void clearCollisionRadiusM() {
      
      collisionRadiusM_ = 0F;
    }

    public static final int COLLISION_HEIGHT_M_FIELD_NUMBER = 4;
    private float collisionHeightM_;
    /**
     * <code>optional float collision_height_m = 4;</code>
     */
    public float getCollisionHeightM() {
      return collisionHeightM_;
    }
    /**
     * <code>optional float collision_height_m = 4;</code>
     */
    private void setCollisionHeightM(float value) {
      
      collisionHeightM_ = value;
    }
    /**
     * <code>optional float collision_height_m = 4;</code>
     */
    private void clearCollisionHeightM() {
      
      collisionHeightM_ = 0F;
    }

    public static final int COLLISION_HEAD_RADIUS_M_FIELD_NUMBER = 5;
    private float collisionHeadRadiusM_;
    /**
     * <code>optional float collision_head_radius_m = 5;</code>
     */
    public float getCollisionHeadRadiusM() {
      return collisionHeadRadiusM_;
    }
    /**
     * <code>optional float collision_head_radius_m = 5;</code>
     */
    private void setCollisionHeadRadiusM(float value) {
      
      collisionHeadRadiusM_ = value;
    }
    /**
     * <code>optional float collision_head_radius_m = 5;</code>
     */
    private void clearCollisionHeadRadiusM() {
      
      collisionHeadRadiusM_ = 0F;
    }

    public static final int MOVEMENT_TYPE_FIELD_NUMBER = 6;
    private int movementType_;
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonMovementType movement_type = 6;</code>
     */
    public int getMovementTypeValue() {
      return movementType_;
    }
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonMovementType movement_type = 6;</code>
     */
    public com.github.aeonlucid.pogoprotos.Enums.PokemonMovementType getMovementType() {
      com.github.aeonlucid.pogoprotos.Enums.PokemonMovementType result = com.github.aeonlucid.pogoprotos.Enums.PokemonMovementType.forNumber(movementType_);
      return result == null ? com.github.aeonlucid.pogoprotos.Enums.PokemonMovementType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonMovementType movement_type = 6;</code>
     */
    private void setMovementTypeValue(int value) {
        movementType_ = value;
    }
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonMovementType movement_type = 6;</code>
     */
    private void setMovementType(com.github.aeonlucid.pogoprotos.Enums.PokemonMovementType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      movementType_ = value.getNumber();
    }
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonMovementType movement_type = 6;</code>
     */
    private void clearMovementType() {
      
      movementType_ = 0;
    }

    public static final int MOVEMENT_TIMER_S_FIELD_NUMBER = 7;
    private float movementTimerS_;
    /**
     * <code>optional float movement_timer_s = 7;</code>
     */
    public float getMovementTimerS() {
      return movementTimerS_;
    }
    /**
     * <code>optional float movement_timer_s = 7;</code>
     */
    private void setMovementTimerS(float value) {
      
      movementTimerS_ = value;
    }
    /**
     * <code>optional float movement_timer_s = 7;</code>
     */
    private void clearMovementTimerS() {
      
      movementTimerS_ = 0F;
    }

    public static final int JUMP_TIME_S_FIELD_NUMBER = 8;
    private float jumpTimeS_;
    /**
     * <code>optional float jump_time_s = 8;</code>
     */
    public float getJumpTimeS() {
      return jumpTimeS_;
    }
    /**
     * <code>optional float jump_time_s = 8;</code>
     */
    private void setJumpTimeS(float value) {
      
      jumpTimeS_ = value;
    }
    /**
     * <code>optional float jump_time_s = 8;</code>
     */
    private void clearJumpTimeS() {
      
      jumpTimeS_ = 0F;
    }

    public static final int ATTACK_TIMER_S_FIELD_NUMBER = 9;
    private float attackTimerS_;
    /**
     * <code>optional float attack_timer_s = 9;</code>
     */
    public float getAttackTimerS() {
      return attackTimerS_;
    }
    /**
     * <code>optional float attack_timer_s = 9;</code>
     */
    private void setAttackTimerS(float value) {
      
      attackTimerS_ = value;
    }
    /**
     * <code>optional float attack_timer_s = 9;</code>
     */
    private void clearAttackTimerS() {
      
      attackTimerS_ = 0F;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (baseCaptureRate_ != 0F) {
        output.writeFloat(1, baseCaptureRate_);
      }
      if (baseFleeRate_ != 0F) {
        output.writeFloat(2, baseFleeRate_);
      }
      if (collisionRadiusM_ != 0F) {
        output.writeFloat(3, collisionRadiusM_);
      }
      if (collisionHeightM_ != 0F) {
        output.writeFloat(4, collisionHeightM_);
      }
      if (collisionHeadRadiusM_ != 0F) {
        output.writeFloat(5, collisionHeadRadiusM_);
      }
      if (movementType_ != com.github.aeonlucid.pogoprotos.Enums.PokemonMovementType.MOVEMENT_STATIC.getNumber()) {
        output.writeEnum(6, movementType_);
      }
      if (movementTimerS_ != 0F) {
        output.writeFloat(7, movementTimerS_);
      }
      if (jumpTimeS_ != 0F) {
        output.writeFloat(8, jumpTimeS_);
      }
      if (attackTimerS_ != 0F) {
        output.writeFloat(9, attackTimerS_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (baseCaptureRate_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, baseCaptureRate_);
      }
      if (baseFleeRate_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, baseFleeRate_);
      }
      if (collisionRadiusM_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, collisionRadiusM_);
      }
      if (collisionHeightM_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, collisionHeightM_);
      }
      if (collisionHeadRadiusM_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, collisionHeadRadiusM_);
      }
      if (movementType_ != com.github.aeonlucid.pogoprotos.Enums.PokemonMovementType.MOVEMENT_STATIC.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, movementType_);
      }
      if (movementTimerS_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, movementTimerS_);
      }
      if (jumpTimeS_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, jumpTimeS_);
      }
      if (attackTimerS_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(9, attackTimerS_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.github.aeonlucid.pogoprotos.settings.master.pokemon.EncounterAttributes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.aeonlucid.pogoprotos.settings.master.pokemon.EncounterAttributes)
        com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributesOrBuilder {
      // Construct using com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional float base_capture_rate = 1;</code>
       */
      public float getBaseCaptureRate() {
        return instance.getBaseCaptureRate();
      }
      /**
       * <code>optional float base_capture_rate = 1;</code>
       */
      public Builder setBaseCaptureRate(float value) {
        copyOnWrite();
        instance.setBaseCaptureRate(value);
        return this;
      }
      /**
       * <code>optional float base_capture_rate = 1;</code>
       */
      public Builder clearBaseCaptureRate() {
        copyOnWrite();
        instance.clearBaseCaptureRate();
        return this;
      }

      /**
       * <code>optional float base_flee_rate = 2;</code>
       */
      public float getBaseFleeRate() {
        return instance.getBaseFleeRate();
      }
      /**
       * <code>optional float base_flee_rate = 2;</code>
       */
      public Builder setBaseFleeRate(float value) {
        copyOnWrite();
        instance.setBaseFleeRate(value);
        return this;
      }
      /**
       * <code>optional float base_flee_rate = 2;</code>
       */
      public Builder clearBaseFleeRate() {
        copyOnWrite();
        instance.clearBaseFleeRate();
        return this;
      }

      /**
       * <code>optional float collision_radius_m = 3;</code>
       */
      public float getCollisionRadiusM() {
        return instance.getCollisionRadiusM();
      }
      /**
       * <code>optional float collision_radius_m = 3;</code>
       */
      public Builder setCollisionRadiusM(float value) {
        copyOnWrite();
        instance.setCollisionRadiusM(value);
        return this;
      }
      /**
       * <code>optional float collision_radius_m = 3;</code>
       */
      public Builder clearCollisionRadiusM() {
        copyOnWrite();
        instance.clearCollisionRadiusM();
        return this;
      }

      /**
       * <code>optional float collision_height_m = 4;</code>
       */
      public float getCollisionHeightM() {
        return instance.getCollisionHeightM();
      }
      /**
       * <code>optional float collision_height_m = 4;</code>
       */
      public Builder setCollisionHeightM(float value) {
        copyOnWrite();
        instance.setCollisionHeightM(value);
        return this;
      }
      /**
       * <code>optional float collision_height_m = 4;</code>
       */
      public Builder clearCollisionHeightM() {
        copyOnWrite();
        instance.clearCollisionHeightM();
        return this;
      }

      /**
       * <code>optional float collision_head_radius_m = 5;</code>
       */
      public float getCollisionHeadRadiusM() {
        return instance.getCollisionHeadRadiusM();
      }
      /**
       * <code>optional float collision_head_radius_m = 5;</code>
       */
      public Builder setCollisionHeadRadiusM(float value) {
        copyOnWrite();
        instance.setCollisionHeadRadiusM(value);
        return this;
      }
      /**
       * <code>optional float collision_head_radius_m = 5;</code>
       */
      public Builder clearCollisionHeadRadiusM() {
        copyOnWrite();
        instance.clearCollisionHeadRadiusM();
        return this;
      }

      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonMovementType movement_type = 6;</code>
       */
      public int getMovementTypeValue() {
        return instance.getMovementTypeValue();
      }
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonMovementType movement_type = 6;</code>
       */
      public Builder setMovementTypeValue(int value) {
        copyOnWrite();
        instance.setMovementTypeValue(value);
        return this;
      }
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonMovementType movement_type = 6;</code>
       */
      public com.github.aeonlucid.pogoprotos.Enums.PokemonMovementType getMovementType() {
        return instance.getMovementType();
      }
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonMovementType movement_type = 6;</code>
       */
      public Builder setMovementType(com.github.aeonlucid.pogoprotos.Enums.PokemonMovementType value) {
        copyOnWrite();
        instance.setMovementType(value);
        return this;
      }
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonMovementType movement_type = 6;</code>
       */
      public Builder clearMovementType() {
        copyOnWrite();
        instance.clearMovementType();
        return this;
      }

      /**
       * <code>optional float movement_timer_s = 7;</code>
       */
      public float getMovementTimerS() {
        return instance.getMovementTimerS();
      }
      /**
       * <code>optional float movement_timer_s = 7;</code>
       */
      public Builder setMovementTimerS(float value) {
        copyOnWrite();
        instance.setMovementTimerS(value);
        return this;
      }
      /**
       * <code>optional float movement_timer_s = 7;</code>
       */
      public Builder clearMovementTimerS() {
        copyOnWrite();
        instance.clearMovementTimerS();
        return this;
      }

      /**
       * <code>optional float jump_time_s = 8;</code>
       */
      public float getJumpTimeS() {
        return instance.getJumpTimeS();
      }
      /**
       * <code>optional float jump_time_s = 8;</code>
       */
      public Builder setJumpTimeS(float value) {
        copyOnWrite();
        instance.setJumpTimeS(value);
        return this;
      }
      /**
       * <code>optional float jump_time_s = 8;</code>
       */
      public Builder clearJumpTimeS() {
        copyOnWrite();
        instance.clearJumpTimeS();
        return this;
      }

      /**
       * <code>optional float attack_timer_s = 9;</code>
       */
      public float getAttackTimerS() {
        return instance.getAttackTimerS();
      }
      /**
       * <code>optional float attack_timer_s = 9;</code>
       */
      public Builder setAttackTimerS(float value) {
        copyOnWrite();
        instance.setAttackTimerS(value);
        return this;
      }
      /**
       * <code>optional float attack_timer_s = 9;</code>
       */
      public Builder clearAttackTimerS() {
        copyOnWrite();
        instance.clearAttackTimerS();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.github.aeonlucid.pogoprotos.settings.master.pokemon.EncounterAttributes)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes other = (com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes) arg1;
          baseCaptureRate_ = visitor.visitFloat(baseCaptureRate_ != 0F, baseCaptureRate_,
              other.baseCaptureRate_ != 0F, other.baseCaptureRate_);
          baseFleeRate_ = visitor.visitFloat(baseFleeRate_ != 0F, baseFleeRate_,
              other.baseFleeRate_ != 0F, other.baseFleeRate_);
          collisionRadiusM_ = visitor.visitFloat(collisionRadiusM_ != 0F, collisionRadiusM_,
              other.collisionRadiusM_ != 0F, other.collisionRadiusM_);
          collisionHeightM_ = visitor.visitFloat(collisionHeightM_ != 0F, collisionHeightM_,
              other.collisionHeightM_ != 0F, other.collisionHeightM_);
          collisionHeadRadiusM_ = visitor.visitFloat(collisionHeadRadiusM_ != 0F, collisionHeadRadiusM_,
              other.collisionHeadRadiusM_ != 0F, other.collisionHeadRadiusM_);
          movementType_ = visitor.visitInt(movementType_ != 0, movementType_,    other.movementType_ != 0, other.movementType_);
          movementTimerS_ = visitor.visitFloat(movementTimerS_ != 0F, movementTimerS_,
              other.movementTimerS_ != 0F, other.movementTimerS_);
          jumpTimeS_ = visitor.visitFloat(jumpTimeS_ != 0F, jumpTimeS_,
              other.jumpTimeS_ != 0F, other.jumpTimeS_);
          attackTimerS_ = visitor.visitFloat(attackTimerS_ != 0F, attackTimerS_,
              other.attackTimerS_ != 0F, other.attackTimerS_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 13: {

                  baseCaptureRate_ = input.readFloat();
                  break;
                }
                case 21: {

                  baseFleeRate_ = input.readFloat();
                  break;
                }
                case 29: {

                  collisionRadiusM_ = input.readFloat();
                  break;
                }
                case 37: {

                  collisionHeightM_ = input.readFloat();
                  break;
                }
                case 45: {

                  collisionHeadRadiusM_ = input.readFloat();
                  break;
                }
                case 48: {
                  int rawValue = input.readEnum();

                  movementType_ = rawValue;
                  break;
                }
                case 61: {

                  movementTimerS_ = input.readFloat();
                  break;
                }
                case 69: {

                  jumpTimeS_ = input.readFloat();
                  break;
                }
                case 77: {

                  attackTimerS_ = input.readFloat();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.github.aeonlucid.pogoprotos.settings.master.pokemon.EncounterAttributes)
    private static final com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EncounterAttributes();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.EncounterAttributes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<EncounterAttributes> PARSER;

    public static com.google.protobuf.Parser<EncounterAttributes> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface StatsAttributesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.aeonlucid.pogoprotos.settings.master.pokemon.StatsAttributes)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional int32 base_stamina = 1;</code>
     */
    int getBaseStamina();

    /**
     * <code>optional int32 base_attack = 2;</code>
     */
    int getBaseAttack();

    /**
     * <code>optional int32 base_defense = 3;</code>
     */
    int getBaseDefense();

    /**
     * <code>optional int32 dodge_energy_delta = 8;</code>
     */
    int getDodgeEnergyDelta();
  }
  /**
   * Protobuf type {@code com.github.aeonlucid.pogoprotos.settings.master.pokemon.StatsAttributes}
   */
  public  static final class StatsAttributes extends
      com.google.protobuf.GeneratedMessageLite<
          StatsAttributes, StatsAttributes.Builder> implements
      // @@protoc_insertion_point(message_implements:com.github.aeonlucid.pogoprotos.settings.master.pokemon.StatsAttributes)
      StatsAttributesOrBuilder {
    private StatsAttributes() {
    }
    public static final int BASE_STAMINA_FIELD_NUMBER = 1;
    private int baseStamina_;
    /**
     * <code>optional int32 base_stamina = 1;</code>
     */
    public int getBaseStamina() {
      return baseStamina_;
    }
    /**
     * <code>optional int32 base_stamina = 1;</code>
     */
    private void setBaseStamina(int value) {
      
      baseStamina_ = value;
    }
    /**
     * <code>optional int32 base_stamina = 1;</code>
     */
    private void clearBaseStamina() {
      
      baseStamina_ = 0;
    }

    public static final int BASE_ATTACK_FIELD_NUMBER = 2;
    private int baseAttack_;
    /**
     * <code>optional int32 base_attack = 2;</code>
     */
    public int getBaseAttack() {
      return baseAttack_;
    }
    /**
     * <code>optional int32 base_attack = 2;</code>
     */
    private void setBaseAttack(int value) {
      
      baseAttack_ = value;
    }
    /**
     * <code>optional int32 base_attack = 2;</code>
     */
    private void clearBaseAttack() {
      
      baseAttack_ = 0;
    }

    public static final int BASE_DEFENSE_FIELD_NUMBER = 3;
    private int baseDefense_;
    /**
     * <code>optional int32 base_defense = 3;</code>
     */
    public int getBaseDefense() {
      return baseDefense_;
    }
    /**
     * <code>optional int32 base_defense = 3;</code>
     */
    private void setBaseDefense(int value) {
      
      baseDefense_ = value;
    }
    /**
     * <code>optional int32 base_defense = 3;</code>
     */
    private void clearBaseDefense() {
      
      baseDefense_ = 0;
    }

    public static final int DODGE_ENERGY_DELTA_FIELD_NUMBER = 8;
    private int dodgeEnergyDelta_;
    /**
     * <code>optional int32 dodge_energy_delta = 8;</code>
     */
    public int getDodgeEnergyDelta() {
      return dodgeEnergyDelta_;
    }
    /**
     * <code>optional int32 dodge_energy_delta = 8;</code>
     */
    private void setDodgeEnergyDelta(int value) {
      
      dodgeEnergyDelta_ = value;
    }
    /**
     * <code>optional int32 dodge_energy_delta = 8;</code>
     */
    private void clearDodgeEnergyDelta() {
      
      dodgeEnergyDelta_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (baseStamina_ != 0) {
        output.writeInt32(1, baseStamina_);
      }
      if (baseAttack_ != 0) {
        output.writeInt32(2, baseAttack_);
      }
      if (baseDefense_ != 0) {
        output.writeInt32(3, baseDefense_);
      }
      if (dodgeEnergyDelta_ != 0) {
        output.writeInt32(8, dodgeEnergyDelta_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (baseStamina_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, baseStamina_);
      }
      if (baseAttack_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, baseAttack_);
      }
      if (baseDefense_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, baseDefense_);
      }
      if (dodgeEnergyDelta_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, dodgeEnergyDelta_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.github.aeonlucid.pogoprotos.settings.master.pokemon.StatsAttributes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.aeonlucid.pogoprotos.settings.master.pokemon.StatsAttributes)
        com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributesOrBuilder {
      // Construct using com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional int32 base_stamina = 1;</code>
       */
      public int getBaseStamina() {
        return instance.getBaseStamina();
      }
      /**
       * <code>optional int32 base_stamina = 1;</code>
       */
      public Builder setBaseStamina(int value) {
        copyOnWrite();
        instance.setBaseStamina(value);
        return this;
      }
      /**
       * <code>optional int32 base_stamina = 1;</code>
       */
      public Builder clearBaseStamina() {
        copyOnWrite();
        instance.clearBaseStamina();
        return this;
      }

      /**
       * <code>optional int32 base_attack = 2;</code>
       */
      public int getBaseAttack() {
        return instance.getBaseAttack();
      }
      /**
       * <code>optional int32 base_attack = 2;</code>
       */
      public Builder setBaseAttack(int value) {
        copyOnWrite();
        instance.setBaseAttack(value);
        return this;
      }
      /**
       * <code>optional int32 base_attack = 2;</code>
       */
      public Builder clearBaseAttack() {
        copyOnWrite();
        instance.clearBaseAttack();
        return this;
      }

      /**
       * <code>optional int32 base_defense = 3;</code>
       */
      public int getBaseDefense() {
        return instance.getBaseDefense();
      }
      /**
       * <code>optional int32 base_defense = 3;</code>
       */
      public Builder setBaseDefense(int value) {
        copyOnWrite();
        instance.setBaseDefense(value);
        return this;
      }
      /**
       * <code>optional int32 base_defense = 3;</code>
       */
      public Builder clearBaseDefense() {
        copyOnWrite();
        instance.clearBaseDefense();
        return this;
      }

      /**
       * <code>optional int32 dodge_energy_delta = 8;</code>
       */
      public int getDodgeEnergyDelta() {
        return instance.getDodgeEnergyDelta();
      }
      /**
       * <code>optional int32 dodge_energy_delta = 8;</code>
       */
      public Builder setDodgeEnergyDelta(int value) {
        copyOnWrite();
        instance.setDodgeEnergyDelta(value);
        return this;
      }
      /**
       * <code>optional int32 dodge_energy_delta = 8;</code>
       */
      public Builder clearDodgeEnergyDelta() {
        copyOnWrite();
        instance.clearDodgeEnergyDelta();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.github.aeonlucid.pogoprotos.settings.master.pokemon.StatsAttributes)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes other = (com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes) arg1;
          baseStamina_ = visitor.visitInt(baseStamina_ != 0, baseStamina_,
              other.baseStamina_ != 0, other.baseStamina_);
          baseAttack_ = visitor.visitInt(baseAttack_ != 0, baseAttack_,
              other.baseAttack_ != 0, other.baseAttack_);
          baseDefense_ = visitor.visitInt(baseDefense_ != 0, baseDefense_,
              other.baseDefense_ != 0, other.baseDefense_);
          dodgeEnergyDelta_ = visitor.visitInt(dodgeEnergyDelta_ != 0, dodgeEnergyDelta_,
              other.dodgeEnergyDelta_ != 0, other.dodgeEnergyDelta_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  baseStamina_ = input.readInt32();
                  break;
                }
                case 16: {

                  baseAttack_ = input.readInt32();
                  break;
                }
                case 24: {

                  baseDefense_ = input.readInt32();
                  break;
                }
                case 64: {

                  dodgeEnergyDelta_ = input.readInt32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.github.aeonlucid.pogoprotos.settings.master.pokemon.StatsAttributes)
    private static final com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new StatsAttributes();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.StatsAttributes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<StatsAttributes> PARSER;

    public static com.google.protobuf.Parser<StatsAttributes> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface CameraAttributesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.aeonlucid.pogoprotos.settings.master.pokemon.CameraAttributes)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional float disk_radius_m = 1;</code>
     */
    float getDiskRadiusM();

    /**
     * <code>optional float cylinder_radius_m = 2;</code>
     */
    float getCylinderRadiusM();

    /**
     * <code>optional float cylinder_height_m = 3;</code>
     */
    float getCylinderHeightM();

    /**
     * <code>optional float cylinder_ground_m = 4;</code>
     */
    float getCylinderGroundM();

    /**
     * <code>optional float shoulder_mode_scale = 5;</code>
     */
    float getShoulderModeScale();
  }
  /**
   * Protobuf type {@code com.github.aeonlucid.pogoprotos.settings.master.pokemon.CameraAttributes}
   */
  public  static final class CameraAttributes extends
      com.google.protobuf.GeneratedMessageLite<
          CameraAttributes, CameraAttributes.Builder> implements
      // @@protoc_insertion_point(message_implements:com.github.aeonlucid.pogoprotos.settings.master.pokemon.CameraAttributes)
      CameraAttributesOrBuilder {
    private CameraAttributes() {
    }
    public static final int DISK_RADIUS_M_FIELD_NUMBER = 1;
    private float diskRadiusM_;
    /**
     * <code>optional float disk_radius_m = 1;</code>
     */
    public float getDiskRadiusM() {
      return diskRadiusM_;
    }
    /**
     * <code>optional float disk_radius_m = 1;</code>
     */
    private void setDiskRadiusM(float value) {
      
      diskRadiusM_ = value;
    }
    /**
     * <code>optional float disk_radius_m = 1;</code>
     */
    private void clearDiskRadiusM() {
      
      diskRadiusM_ = 0F;
    }

    public static final int CYLINDER_RADIUS_M_FIELD_NUMBER = 2;
    private float cylinderRadiusM_;
    /**
     * <code>optional float cylinder_radius_m = 2;</code>
     */
    public float getCylinderRadiusM() {
      return cylinderRadiusM_;
    }
    /**
     * <code>optional float cylinder_radius_m = 2;</code>
     */
    private void setCylinderRadiusM(float value) {
      
      cylinderRadiusM_ = value;
    }
    /**
     * <code>optional float cylinder_radius_m = 2;</code>
     */
    private void clearCylinderRadiusM() {
      
      cylinderRadiusM_ = 0F;
    }

    public static final int CYLINDER_HEIGHT_M_FIELD_NUMBER = 3;
    private float cylinderHeightM_;
    /**
     * <code>optional float cylinder_height_m = 3;</code>
     */
    public float getCylinderHeightM() {
      return cylinderHeightM_;
    }
    /**
     * <code>optional float cylinder_height_m = 3;</code>
     */
    private void setCylinderHeightM(float value) {
      
      cylinderHeightM_ = value;
    }
    /**
     * <code>optional float cylinder_height_m = 3;</code>
     */
    private void clearCylinderHeightM() {
      
      cylinderHeightM_ = 0F;
    }

    public static final int CYLINDER_GROUND_M_FIELD_NUMBER = 4;
    private float cylinderGroundM_;
    /**
     * <code>optional float cylinder_ground_m = 4;</code>
     */
    public float getCylinderGroundM() {
      return cylinderGroundM_;
    }
    /**
     * <code>optional float cylinder_ground_m = 4;</code>
     */
    private void setCylinderGroundM(float value) {
      
      cylinderGroundM_ = value;
    }
    /**
     * <code>optional float cylinder_ground_m = 4;</code>
     */
    private void clearCylinderGroundM() {
      
      cylinderGroundM_ = 0F;
    }

    public static final int SHOULDER_MODE_SCALE_FIELD_NUMBER = 5;
    private float shoulderModeScale_;
    /**
     * <code>optional float shoulder_mode_scale = 5;</code>
     */
    public float getShoulderModeScale() {
      return shoulderModeScale_;
    }
    /**
     * <code>optional float shoulder_mode_scale = 5;</code>
     */
    private void setShoulderModeScale(float value) {
      
      shoulderModeScale_ = value;
    }
    /**
     * <code>optional float shoulder_mode_scale = 5;</code>
     */
    private void clearShoulderModeScale() {
      
      shoulderModeScale_ = 0F;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (diskRadiusM_ != 0F) {
        output.writeFloat(1, diskRadiusM_);
      }
      if (cylinderRadiusM_ != 0F) {
        output.writeFloat(2, cylinderRadiusM_);
      }
      if (cylinderHeightM_ != 0F) {
        output.writeFloat(3, cylinderHeightM_);
      }
      if (cylinderGroundM_ != 0F) {
        output.writeFloat(4, cylinderGroundM_);
      }
      if (shoulderModeScale_ != 0F) {
        output.writeFloat(5, shoulderModeScale_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (diskRadiusM_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, diskRadiusM_);
      }
      if (cylinderRadiusM_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, cylinderRadiusM_);
      }
      if (cylinderHeightM_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, cylinderHeightM_);
      }
      if (cylinderGroundM_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, cylinderGroundM_);
      }
      if (shoulderModeScale_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, shoulderModeScale_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.github.aeonlucid.pogoprotos.settings.master.pokemon.CameraAttributes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.aeonlucid.pogoprotos.settings.master.pokemon.CameraAttributes)
        com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributesOrBuilder {
      // Construct using com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional float disk_radius_m = 1;</code>
       */
      public float getDiskRadiusM() {
        return instance.getDiskRadiusM();
      }
      /**
       * <code>optional float disk_radius_m = 1;</code>
       */
      public Builder setDiskRadiusM(float value) {
        copyOnWrite();
        instance.setDiskRadiusM(value);
        return this;
      }
      /**
       * <code>optional float disk_radius_m = 1;</code>
       */
      public Builder clearDiskRadiusM() {
        copyOnWrite();
        instance.clearDiskRadiusM();
        return this;
      }

      /**
       * <code>optional float cylinder_radius_m = 2;</code>
       */
      public float getCylinderRadiusM() {
        return instance.getCylinderRadiusM();
      }
      /**
       * <code>optional float cylinder_radius_m = 2;</code>
       */
      public Builder setCylinderRadiusM(float value) {
        copyOnWrite();
        instance.setCylinderRadiusM(value);
        return this;
      }
      /**
       * <code>optional float cylinder_radius_m = 2;</code>
       */
      public Builder clearCylinderRadiusM() {
        copyOnWrite();
        instance.clearCylinderRadiusM();
        return this;
      }

      /**
       * <code>optional float cylinder_height_m = 3;</code>
       */
      public float getCylinderHeightM() {
        return instance.getCylinderHeightM();
      }
      /**
       * <code>optional float cylinder_height_m = 3;</code>
       */
      public Builder setCylinderHeightM(float value) {
        copyOnWrite();
        instance.setCylinderHeightM(value);
        return this;
      }
      /**
       * <code>optional float cylinder_height_m = 3;</code>
       */
      public Builder clearCylinderHeightM() {
        copyOnWrite();
        instance.clearCylinderHeightM();
        return this;
      }

      /**
       * <code>optional float cylinder_ground_m = 4;</code>
       */
      public float getCylinderGroundM() {
        return instance.getCylinderGroundM();
      }
      /**
       * <code>optional float cylinder_ground_m = 4;</code>
       */
      public Builder setCylinderGroundM(float value) {
        copyOnWrite();
        instance.setCylinderGroundM(value);
        return this;
      }
      /**
       * <code>optional float cylinder_ground_m = 4;</code>
       */
      public Builder clearCylinderGroundM() {
        copyOnWrite();
        instance.clearCylinderGroundM();
        return this;
      }

      /**
       * <code>optional float shoulder_mode_scale = 5;</code>
       */
      public float getShoulderModeScale() {
        return instance.getShoulderModeScale();
      }
      /**
       * <code>optional float shoulder_mode_scale = 5;</code>
       */
      public Builder setShoulderModeScale(float value) {
        copyOnWrite();
        instance.setShoulderModeScale(value);
        return this;
      }
      /**
       * <code>optional float shoulder_mode_scale = 5;</code>
       */
      public Builder clearShoulderModeScale() {
        copyOnWrite();
        instance.clearShoulderModeScale();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.github.aeonlucid.pogoprotos.settings.master.pokemon.CameraAttributes)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes other = (com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes) arg1;
          diskRadiusM_ = visitor.visitFloat(diskRadiusM_ != 0F, diskRadiusM_,
              other.diskRadiusM_ != 0F, other.diskRadiusM_);
          cylinderRadiusM_ = visitor.visitFloat(cylinderRadiusM_ != 0F, cylinderRadiusM_,
              other.cylinderRadiusM_ != 0F, other.cylinderRadiusM_);
          cylinderHeightM_ = visitor.visitFloat(cylinderHeightM_ != 0F, cylinderHeightM_,
              other.cylinderHeightM_ != 0F, other.cylinderHeightM_);
          cylinderGroundM_ = visitor.visitFloat(cylinderGroundM_ != 0F, cylinderGroundM_,
              other.cylinderGroundM_ != 0F, other.cylinderGroundM_);
          shoulderModeScale_ = visitor.visitFloat(shoulderModeScale_ != 0F, shoulderModeScale_,
              other.shoulderModeScale_ != 0F, other.shoulderModeScale_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 13: {

                  diskRadiusM_ = input.readFloat();
                  break;
                }
                case 21: {

                  cylinderRadiusM_ = input.readFloat();
                  break;
                }
                case 29: {

                  cylinderHeightM_ = input.readFloat();
                  break;
                }
                case 37: {

                  cylinderGroundM_ = input.readFloat();
                  break;
                }
                case 45: {

                  shoulderModeScale_ = input.readFloat();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.github.aeonlucid.pogoprotos.settings.master.pokemon.CameraAttributes)
    private static final com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CameraAttributes();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.github.aeonlucid.pogoprotos.settings.master.Pokemon.CameraAttributes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<CameraAttributes> PARSER;

    public static com.google.protobuf.Parser<CameraAttributes> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
