// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/github/aeonlucid/pogoprotos/inventory/Item.proto

package com.github.aeonlucid.pogoprotos.inventory;

public final class Item {
  private Item() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code com.github.aeonlucid.pogoprotos.inventory.item.ItemId}
   */
  public enum ItemId
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>ITEM_UNKNOWN = 0;</code>
     */
    ITEM_UNKNOWN(0),
    /**
     * <code>ITEM_POKE_BALL = 1;</code>
     */
    ITEM_POKE_BALL(1),
    /**
     * <code>ITEM_GREAT_BALL = 2;</code>
     */
    ITEM_GREAT_BALL(2),
    /**
     * <code>ITEM_ULTRA_BALL = 3;</code>
     */
    ITEM_ULTRA_BALL(3),
    /**
     * <code>ITEM_MASTER_BALL = 4;</code>
     */
    ITEM_MASTER_BALL(4),
    /**
     * <code>ITEM_POTION = 101;</code>
     */
    ITEM_POTION(101),
    /**
     * <code>ITEM_SUPER_POTION = 102;</code>
     */
    ITEM_SUPER_POTION(102),
    /**
     * <code>ITEM_HYPER_POTION = 103;</code>
     */
    ITEM_HYPER_POTION(103),
    /**
     * <code>ITEM_MAX_POTION = 104;</code>
     */
    ITEM_MAX_POTION(104),
    /**
     * <code>ITEM_REVIVE = 201;</code>
     */
    ITEM_REVIVE(201),
    /**
     * <code>ITEM_MAX_REVIVE = 202;</code>
     */
    ITEM_MAX_REVIVE(202),
    /**
     * <code>ITEM_LUCKY_EGG = 301;</code>
     */
    ITEM_LUCKY_EGG(301),
    /**
     * <code>ITEM_INCENSE_ORDINARY = 401;</code>
     */
    ITEM_INCENSE_ORDINARY(401),
    /**
     * <code>ITEM_INCENSE_SPICY = 402;</code>
     */
    ITEM_INCENSE_SPICY(402),
    /**
     * <code>ITEM_INCENSE_COOL = 403;</code>
     */
    ITEM_INCENSE_COOL(403),
    /**
     * <code>ITEM_INCENSE_FLORAL = 404;</code>
     */
    ITEM_INCENSE_FLORAL(404),
    /**
     * <code>ITEM_TROY_DISK = 501;</code>
     */
    ITEM_TROY_DISK(501),
    /**
     * <code>ITEM_X_ATTACK = 602;</code>
     */
    ITEM_X_ATTACK(602),
    /**
     * <code>ITEM_X_DEFENSE = 603;</code>
     */
    ITEM_X_DEFENSE(603),
    /**
     * <code>ITEM_X_MIRACLE = 604;</code>
     */
    ITEM_X_MIRACLE(604),
    /**
     * <code>ITEM_RAZZ_BERRY = 701;</code>
     */
    ITEM_RAZZ_BERRY(701),
    /**
     * <code>ITEM_BLUK_BERRY = 702;</code>
     */
    ITEM_BLUK_BERRY(702),
    /**
     * <code>ITEM_NANAB_BERRY = 703;</code>
     */
    ITEM_NANAB_BERRY(703),
    /**
     * <code>ITEM_WEPAR_BERRY = 704;</code>
     */
    ITEM_WEPAR_BERRY(704),
    /**
     * <code>ITEM_PINAP_BERRY = 705;</code>
     */
    ITEM_PINAP_BERRY(705),
    /**
     * <code>ITEM_SPECIAL_CAMERA = 801;</code>
     */
    ITEM_SPECIAL_CAMERA(801),
    /**
     * <code>ITEM_INCUBATOR_BASIC_UNLIMITED = 901;</code>
     */
    ITEM_INCUBATOR_BASIC_UNLIMITED(901),
    /**
     * <code>ITEM_INCUBATOR_BASIC = 902;</code>
     */
    ITEM_INCUBATOR_BASIC(902),
    /**
     * <code>ITEM_POKEMON_STORAGE_UPGRADE = 1001;</code>
     */
    ITEM_POKEMON_STORAGE_UPGRADE(1001),
    /**
     * <code>ITEM_ITEM_STORAGE_UPGRADE = 1002;</code>
     */
    ITEM_ITEM_STORAGE_UPGRADE(1002),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ITEM_UNKNOWN = 0;</code>
     */
    public static final int ITEM_UNKNOWN_VALUE = 0;
    /**
     * <code>ITEM_POKE_BALL = 1;</code>
     */
    public static final int ITEM_POKE_BALL_VALUE = 1;
    /**
     * <code>ITEM_GREAT_BALL = 2;</code>
     */
    public static final int ITEM_GREAT_BALL_VALUE = 2;
    /**
     * <code>ITEM_ULTRA_BALL = 3;</code>
     */
    public static final int ITEM_ULTRA_BALL_VALUE = 3;
    /**
     * <code>ITEM_MASTER_BALL = 4;</code>
     */
    public static final int ITEM_MASTER_BALL_VALUE = 4;
    /**
     * <code>ITEM_POTION = 101;</code>
     */
    public static final int ITEM_POTION_VALUE = 101;
    /**
     * <code>ITEM_SUPER_POTION = 102;</code>
     */
    public static final int ITEM_SUPER_POTION_VALUE = 102;
    /**
     * <code>ITEM_HYPER_POTION = 103;</code>
     */
    public static final int ITEM_HYPER_POTION_VALUE = 103;
    /**
     * <code>ITEM_MAX_POTION = 104;</code>
     */
    public static final int ITEM_MAX_POTION_VALUE = 104;
    /**
     * <code>ITEM_REVIVE = 201;</code>
     */
    public static final int ITEM_REVIVE_VALUE = 201;
    /**
     * <code>ITEM_MAX_REVIVE = 202;</code>
     */
    public static final int ITEM_MAX_REVIVE_VALUE = 202;
    /**
     * <code>ITEM_LUCKY_EGG = 301;</code>
     */
    public static final int ITEM_LUCKY_EGG_VALUE = 301;
    /**
     * <code>ITEM_INCENSE_ORDINARY = 401;</code>
     */
    public static final int ITEM_INCENSE_ORDINARY_VALUE = 401;
    /**
     * <code>ITEM_INCENSE_SPICY = 402;</code>
     */
    public static final int ITEM_INCENSE_SPICY_VALUE = 402;
    /**
     * <code>ITEM_INCENSE_COOL = 403;</code>
     */
    public static final int ITEM_INCENSE_COOL_VALUE = 403;
    /**
     * <code>ITEM_INCENSE_FLORAL = 404;</code>
     */
    public static final int ITEM_INCENSE_FLORAL_VALUE = 404;
    /**
     * <code>ITEM_TROY_DISK = 501;</code>
     */
    public static final int ITEM_TROY_DISK_VALUE = 501;
    /**
     * <code>ITEM_X_ATTACK = 602;</code>
     */
    public static final int ITEM_X_ATTACK_VALUE = 602;
    /**
     * <code>ITEM_X_DEFENSE = 603;</code>
     */
    public static final int ITEM_X_DEFENSE_VALUE = 603;
    /**
     * <code>ITEM_X_MIRACLE = 604;</code>
     */
    public static final int ITEM_X_MIRACLE_VALUE = 604;
    /**
     * <code>ITEM_RAZZ_BERRY = 701;</code>
     */
    public static final int ITEM_RAZZ_BERRY_VALUE = 701;
    /**
     * <code>ITEM_BLUK_BERRY = 702;</code>
     */
    public static final int ITEM_BLUK_BERRY_VALUE = 702;
    /**
     * <code>ITEM_NANAB_BERRY = 703;</code>
     */
    public static final int ITEM_NANAB_BERRY_VALUE = 703;
    /**
     * <code>ITEM_WEPAR_BERRY = 704;</code>
     */
    public static final int ITEM_WEPAR_BERRY_VALUE = 704;
    /**
     * <code>ITEM_PINAP_BERRY = 705;</code>
     */
    public static final int ITEM_PINAP_BERRY_VALUE = 705;
    /**
     * <code>ITEM_SPECIAL_CAMERA = 801;</code>
     */
    public static final int ITEM_SPECIAL_CAMERA_VALUE = 801;
    /**
     * <code>ITEM_INCUBATOR_BASIC_UNLIMITED = 901;</code>
     */
    public static final int ITEM_INCUBATOR_BASIC_UNLIMITED_VALUE = 901;
    /**
     * <code>ITEM_INCUBATOR_BASIC = 902;</code>
     */
    public static final int ITEM_INCUBATOR_BASIC_VALUE = 902;
    /**
     * <code>ITEM_POKEMON_STORAGE_UPGRADE = 1001;</code>
     */
    public static final int ITEM_POKEMON_STORAGE_UPGRADE_VALUE = 1001;
    /**
     * <code>ITEM_ITEM_STORAGE_UPGRADE = 1002;</code>
     */
    public static final int ITEM_ITEM_STORAGE_UPGRADE_VALUE = 1002;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ItemId valueOf(int value) {
      return forNumber(value);
    }

    public static ItemId forNumber(int value) {
      switch (value) {
        case 0: return ITEM_UNKNOWN;
        case 1: return ITEM_POKE_BALL;
        case 2: return ITEM_GREAT_BALL;
        case 3: return ITEM_ULTRA_BALL;
        case 4: return ITEM_MASTER_BALL;
        case 101: return ITEM_POTION;
        case 102: return ITEM_SUPER_POTION;
        case 103: return ITEM_HYPER_POTION;
        case 104: return ITEM_MAX_POTION;
        case 201: return ITEM_REVIVE;
        case 202: return ITEM_MAX_REVIVE;
        case 301: return ITEM_LUCKY_EGG;
        case 401: return ITEM_INCENSE_ORDINARY;
        case 402: return ITEM_INCENSE_SPICY;
        case 403: return ITEM_INCENSE_COOL;
        case 404: return ITEM_INCENSE_FLORAL;
        case 501: return ITEM_TROY_DISK;
        case 602: return ITEM_X_ATTACK;
        case 603: return ITEM_X_DEFENSE;
        case 604: return ITEM_X_MIRACLE;
        case 701: return ITEM_RAZZ_BERRY;
        case 702: return ITEM_BLUK_BERRY;
        case 703: return ITEM_NANAB_BERRY;
        case 704: return ITEM_WEPAR_BERRY;
        case 705: return ITEM_PINAP_BERRY;
        case 801: return ITEM_SPECIAL_CAMERA;
        case 901: return ITEM_INCUBATOR_BASIC_UNLIMITED;
        case 902: return ITEM_INCUBATOR_BASIC;
        case 1001: return ITEM_POKEMON_STORAGE_UPGRADE;
        case 1002: return ITEM_ITEM_STORAGE_UPGRADE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ItemId>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ItemId> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ItemId>() {
            public ItemId findValueByNumber(int number) {
              return ItemId.forNumber(number);
            }
          };

    private final int value;

    private ItemId(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.github.aeonlucid.pogoprotos.inventory.item.ItemId)
  }

  /**
   * Protobuf enum {@code com.github.aeonlucid.pogoprotos.inventory.item.ItemType}
   */
  public enum ItemType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>ITEM_TYPE_NONE = 0;</code>
     */
    ITEM_TYPE_NONE(0),
    /**
     * <code>ITEM_TYPE_POKEBALL = 1;</code>
     */
    ITEM_TYPE_POKEBALL(1),
    /**
     * <code>ITEM_TYPE_POTION = 2;</code>
     */
    ITEM_TYPE_POTION(2),
    /**
     * <code>ITEM_TYPE_REVIVE = 3;</code>
     */
    ITEM_TYPE_REVIVE(3),
    /**
     * <code>ITEM_TYPE_MAP = 4;</code>
     */
    ITEM_TYPE_MAP(4),
    /**
     * <code>ITEM_TYPE_BATTLE = 5;</code>
     */
    ITEM_TYPE_BATTLE(5),
    /**
     * <code>ITEM_TYPE_FOOD = 6;</code>
     */
    ITEM_TYPE_FOOD(6),
    /**
     * <code>ITEM_TYPE_CAMERA = 7;</code>
     */
    ITEM_TYPE_CAMERA(7),
    /**
     * <code>ITEM_TYPE_DISK = 8;</code>
     */
    ITEM_TYPE_DISK(8),
    /**
     * <code>ITEM_TYPE_INCUBATOR = 9;</code>
     */
    ITEM_TYPE_INCUBATOR(9),
    /**
     * <code>ITEM_TYPE_INCENSE = 10;</code>
     */
    ITEM_TYPE_INCENSE(10),
    /**
     * <code>ITEM_TYPE_XP_BOOST = 11;</code>
     */
    ITEM_TYPE_XP_BOOST(11),
    /**
     * <code>ITEM_TYPE_INVENTORY_UPGRADE = 12;</code>
     */
    ITEM_TYPE_INVENTORY_UPGRADE(12),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ITEM_TYPE_NONE = 0;</code>
     */
    public static final int ITEM_TYPE_NONE_VALUE = 0;
    /**
     * <code>ITEM_TYPE_POKEBALL = 1;</code>
     */
    public static final int ITEM_TYPE_POKEBALL_VALUE = 1;
    /**
     * <code>ITEM_TYPE_POTION = 2;</code>
     */
    public static final int ITEM_TYPE_POTION_VALUE = 2;
    /**
     * <code>ITEM_TYPE_REVIVE = 3;</code>
     */
    public static final int ITEM_TYPE_REVIVE_VALUE = 3;
    /**
     * <code>ITEM_TYPE_MAP = 4;</code>
     */
    public static final int ITEM_TYPE_MAP_VALUE = 4;
    /**
     * <code>ITEM_TYPE_BATTLE = 5;</code>
     */
    public static final int ITEM_TYPE_BATTLE_VALUE = 5;
    /**
     * <code>ITEM_TYPE_FOOD = 6;</code>
     */
    public static final int ITEM_TYPE_FOOD_VALUE = 6;
    /**
     * <code>ITEM_TYPE_CAMERA = 7;</code>
     */
    public static final int ITEM_TYPE_CAMERA_VALUE = 7;
    /**
     * <code>ITEM_TYPE_DISK = 8;</code>
     */
    public static final int ITEM_TYPE_DISK_VALUE = 8;
    /**
     * <code>ITEM_TYPE_INCUBATOR = 9;</code>
     */
    public static final int ITEM_TYPE_INCUBATOR_VALUE = 9;
    /**
     * <code>ITEM_TYPE_INCENSE = 10;</code>
     */
    public static final int ITEM_TYPE_INCENSE_VALUE = 10;
    /**
     * <code>ITEM_TYPE_XP_BOOST = 11;</code>
     */
    public static final int ITEM_TYPE_XP_BOOST_VALUE = 11;
    /**
     * <code>ITEM_TYPE_INVENTORY_UPGRADE = 12;</code>
     */
    public static final int ITEM_TYPE_INVENTORY_UPGRADE_VALUE = 12;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ItemType valueOf(int value) {
      return forNumber(value);
    }

    public static ItemType forNumber(int value) {
      switch (value) {
        case 0: return ITEM_TYPE_NONE;
        case 1: return ITEM_TYPE_POKEBALL;
        case 2: return ITEM_TYPE_POTION;
        case 3: return ITEM_TYPE_REVIVE;
        case 4: return ITEM_TYPE_MAP;
        case 5: return ITEM_TYPE_BATTLE;
        case 6: return ITEM_TYPE_FOOD;
        case 7: return ITEM_TYPE_CAMERA;
        case 8: return ITEM_TYPE_DISK;
        case 9: return ITEM_TYPE_INCUBATOR;
        case 10: return ITEM_TYPE_INCENSE;
        case 11: return ITEM_TYPE_XP_BOOST;
        case 12: return ITEM_TYPE_INVENTORY_UPGRADE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ItemType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ItemType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ItemType>() {
            public ItemType findValueByNumber(int number) {
              return ItemType.forNumber(number);
            }
          };

    private final int value;

    private ItemType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.github.aeonlucid.pogoprotos.inventory.item.ItemType)
  }

  public interface ItemDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.aeonlucid.pogoprotos.inventory.item.ItemData)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
     */
    int getItemIdValue();
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
     */
    com.github.aeonlucid.pogoprotos.inventory.Item.ItemId getItemId();

    /**
     * <code>optional int32 count = 2;</code>
     */
    int getCount();

    /**
     * <code>optional bool unseen = 3;</code>
     */
    boolean getUnseen();
  }
  /**
   * Protobuf type {@code com.github.aeonlucid.pogoprotos.inventory.item.ItemData}
   */
  public  static final class ItemData extends
      com.google.protobuf.GeneratedMessageLite<
          ItemData, ItemData.Builder> implements
      // @@protoc_insertion_point(message_implements:com.github.aeonlucid.pogoprotos.inventory.item.ItemData)
      ItemDataOrBuilder {
    private ItemData() {
    }
    public static final int ITEM_ID_FIELD_NUMBER = 1;
    private int itemId_;
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
     */
    public int getItemIdValue() {
      return itemId_;
    }
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
     */
    public com.github.aeonlucid.pogoprotos.inventory.Item.ItemId getItemId() {
      com.github.aeonlucid.pogoprotos.inventory.Item.ItemId result = com.github.aeonlucid.pogoprotos.inventory.Item.ItemId.forNumber(itemId_);
      return result == null ? com.github.aeonlucid.pogoprotos.inventory.Item.ItemId.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
     */
    private void setItemIdValue(int value) {
        itemId_ = value;
    }
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
     */
    private void setItemId(com.github.aeonlucid.pogoprotos.inventory.Item.ItemId value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      itemId_ = value.getNumber();
    }
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
     */
    private void clearItemId() {
      
      itemId_ = 0;
    }

    public static final int COUNT_FIELD_NUMBER = 2;
    private int count_;
    /**
     * <code>optional int32 count = 2;</code>
     */
    public int getCount() {
      return count_;
    }
    /**
     * <code>optional int32 count = 2;</code>
     */
    private void setCount(int value) {
      
      count_ = value;
    }
    /**
     * <code>optional int32 count = 2;</code>
     */
    private void clearCount() {
      
      count_ = 0;
    }

    public static final int UNSEEN_FIELD_NUMBER = 3;
    private boolean unseen_;
    /**
     * <code>optional bool unseen = 3;</code>
     */
    public boolean getUnseen() {
      return unseen_;
    }
    /**
     * <code>optional bool unseen = 3;</code>
     */
    private void setUnseen(boolean value) {
      
      unseen_ = value;
    }
    /**
     * <code>optional bool unseen = 3;</code>
     */
    private void clearUnseen() {
      
      unseen_ = false;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (itemId_ != com.github.aeonlucid.pogoprotos.inventory.Item.ItemId.ITEM_UNKNOWN.getNumber()) {
        output.writeEnum(1, itemId_);
      }
      if (count_ != 0) {
        output.writeInt32(2, count_);
      }
      if (unseen_ != false) {
        output.writeBool(3, unseen_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (itemId_ != com.github.aeonlucid.pogoprotos.inventory.Item.ItemId.ITEM_UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, itemId_);
      }
      if (count_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, count_);
      }
      if (unseen_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, unseen_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.aeonlucid.pogoprotos.inventory.Item.ItemData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.github.aeonlucid.pogoprotos.inventory.item.ItemData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.github.aeonlucid.pogoprotos.inventory.Item.ItemData, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.aeonlucid.pogoprotos.inventory.item.ItemData)
        com.github.aeonlucid.pogoprotos.inventory.Item.ItemDataOrBuilder {
      // Construct using com.github.aeonlucid.pogoprotos.inventory.Item.ItemData.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
       */
      public int getItemIdValue() {
        return instance.getItemIdValue();
      }
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
       */
      public Builder setItemIdValue(int value) {
        copyOnWrite();
        instance.setItemIdValue(value);
        return this;
      }
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
       */
      public com.github.aeonlucid.pogoprotos.inventory.Item.ItemId getItemId() {
        return instance.getItemId();
      }
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
       */
      public Builder setItemId(com.github.aeonlucid.pogoprotos.inventory.Item.ItemId value) {
        copyOnWrite();
        instance.setItemId(value);
        return this;
      }
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
       */
      public Builder clearItemId() {
        copyOnWrite();
        instance.clearItemId();
        return this;
      }

      /**
       * <code>optional int32 count = 2;</code>
       */
      public int getCount() {
        return instance.getCount();
      }
      /**
       * <code>optional int32 count = 2;</code>
       */
      public Builder setCount(int value) {
        copyOnWrite();
        instance.setCount(value);
        return this;
      }
      /**
       * <code>optional int32 count = 2;</code>
       */
      public Builder clearCount() {
        copyOnWrite();
        instance.clearCount();
        return this;
      }

      /**
       * <code>optional bool unseen = 3;</code>
       */
      public boolean getUnseen() {
        return instance.getUnseen();
      }
      /**
       * <code>optional bool unseen = 3;</code>
       */
      public Builder setUnseen(boolean value) {
        copyOnWrite();
        instance.setUnseen(value);
        return this;
      }
      /**
       * <code>optional bool unseen = 3;</code>
       */
      public Builder clearUnseen() {
        copyOnWrite();
        instance.clearUnseen();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.github.aeonlucid.pogoprotos.inventory.item.ItemData)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.github.aeonlucid.pogoprotos.inventory.Item.ItemData();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.github.aeonlucid.pogoprotos.inventory.Item.ItemData other = (com.github.aeonlucid.pogoprotos.inventory.Item.ItemData) arg1;
          itemId_ = visitor.visitInt(itemId_ != 0, itemId_,    other.itemId_ != 0, other.itemId_);
          count_ = visitor.visitInt(count_ != 0, count_,
              other.count_ != 0, other.count_);
          unseen_ = visitor.visitBoolean(unseen_ != false, unseen_,
              other.unseen_ != false, other.unseen_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  int rawValue = input.readEnum();

                  itemId_ = rawValue;
                  break;
                }
                case 16: {

                  count_ = input.readInt32();
                  break;
                }
                case 24: {

                  unseen_ = input.readBool();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.github.aeonlucid.pogoprotos.inventory.Item.ItemData.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.github.aeonlucid.pogoprotos.inventory.item.ItemData)
    private static final com.github.aeonlucid.pogoprotos.inventory.Item.ItemData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ItemData();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ItemData> PARSER;

    public static com.google.protobuf.Parser<ItemData> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ItemAwardOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.aeonlucid.pogoprotos.inventory.item.ItemAward)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
     */
    int getItemIdValue();
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
     */
    com.github.aeonlucid.pogoprotos.inventory.Item.ItemId getItemId();

    /**
     * <code>optional int32 item_count = 2;</code>
     */
    int getItemCount();
  }
  /**
   * Protobuf type {@code com.github.aeonlucid.pogoprotos.inventory.item.ItemAward}
   */
  public  static final class ItemAward extends
      com.google.protobuf.GeneratedMessageLite<
          ItemAward, ItemAward.Builder> implements
      // @@protoc_insertion_point(message_implements:com.github.aeonlucid.pogoprotos.inventory.item.ItemAward)
      ItemAwardOrBuilder {
    private ItemAward() {
    }
    public static final int ITEM_ID_FIELD_NUMBER = 1;
    private int itemId_;
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
     */
    public int getItemIdValue() {
      return itemId_;
    }
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
     */
    public com.github.aeonlucid.pogoprotos.inventory.Item.ItemId getItemId() {
      com.github.aeonlucid.pogoprotos.inventory.Item.ItemId result = com.github.aeonlucid.pogoprotos.inventory.Item.ItemId.forNumber(itemId_);
      return result == null ? com.github.aeonlucid.pogoprotos.inventory.Item.ItemId.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
     */
    private void setItemIdValue(int value) {
        itemId_ = value;
    }
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
     */
    private void setItemId(com.github.aeonlucid.pogoprotos.inventory.Item.ItemId value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      itemId_ = value.getNumber();
    }
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
     */
    private void clearItemId() {
      
      itemId_ = 0;
    }

    public static final int ITEM_COUNT_FIELD_NUMBER = 2;
    private int itemCount_;
    /**
     * <code>optional int32 item_count = 2;</code>
     */
    public int getItemCount() {
      return itemCount_;
    }
    /**
     * <code>optional int32 item_count = 2;</code>
     */
    private void setItemCount(int value) {
      
      itemCount_ = value;
    }
    /**
     * <code>optional int32 item_count = 2;</code>
     */
    private void clearItemCount() {
      
      itemCount_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (itemId_ != com.github.aeonlucid.pogoprotos.inventory.Item.ItemId.ITEM_UNKNOWN.getNumber()) {
        output.writeEnum(1, itemId_);
      }
      if (itemCount_ != 0) {
        output.writeInt32(2, itemCount_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (itemId_ != com.github.aeonlucid.pogoprotos.inventory.Item.ItemId.ITEM_UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, itemId_);
      }
      if (itemCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, itemCount_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.github.aeonlucid.pogoprotos.inventory.item.ItemAward}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.aeonlucid.pogoprotos.inventory.item.ItemAward)
        com.github.aeonlucid.pogoprotos.inventory.Item.ItemAwardOrBuilder {
      // Construct using com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
       */
      public int getItemIdValue() {
        return instance.getItemIdValue();
      }
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
       */
      public Builder setItemIdValue(int value) {
        copyOnWrite();
        instance.setItemIdValue(value);
        return this;
      }
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
       */
      public com.github.aeonlucid.pogoprotos.inventory.Item.ItemId getItemId() {
        return instance.getItemId();
      }
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
       */
      public Builder setItemId(com.github.aeonlucid.pogoprotos.inventory.Item.ItemId value) {
        copyOnWrite();
        instance.setItemId(value);
        return this;
      }
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
       */
      public Builder clearItemId() {
        copyOnWrite();
        instance.clearItemId();
        return this;
      }

      /**
       * <code>optional int32 item_count = 2;</code>
       */
      public int getItemCount() {
        return instance.getItemCount();
      }
      /**
       * <code>optional int32 item_count = 2;</code>
       */
      public Builder setItemCount(int value) {
        copyOnWrite();
        instance.setItemCount(value);
        return this;
      }
      /**
       * <code>optional int32 item_count = 2;</code>
       */
      public Builder clearItemCount() {
        copyOnWrite();
        instance.clearItemCount();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.github.aeonlucid.pogoprotos.inventory.item.ItemAward)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward other = (com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward) arg1;
          itemId_ = visitor.visitInt(itemId_ != 0, itemId_,    other.itemId_ != 0, other.itemId_);
          itemCount_ = visitor.visitInt(itemCount_ != 0, itemCount_,
              other.itemCount_ != 0, other.itemCount_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  int rawValue = input.readEnum();

                  itemId_ = rawValue;
                  break;
                }
                case 16: {

                  itemCount_ = input.readInt32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.github.aeonlucid.pogoprotos.inventory.item.ItemAward)
    private static final com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ItemAward();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ItemAward> PARSER;

    public static com.google.protobuf.Parser<ItemAward> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
