// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/github/aeonlucid/pogoprotos/map/Pokemon.proto

package com.github.aeonlucid.pogoprotos.map;

public final class Pokemon {
  private Pokemon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface NearbyPokemonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.aeonlucid.pogoprotos.map.pokemon.NearbyPokemon)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonId pokemon_id = 1;</code>
     */
    int getPokemonIdValue();
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonId pokemon_id = 1;</code>
     */
    com.github.aeonlucid.pogoprotos.Enums.PokemonId getPokemonId();

    /**
     * <code>optional float distance_in_meters = 2;</code>
     */
    float getDistanceInMeters();

    /**
     * <code>optional fixed64 encounter_id = 3;</code>
     */
    long getEncounterId();

    /**
     * <code>optional string fort_id = 4;</code>
     */
    java.lang.String getFortId();
    /**
     * <code>optional string fort_id = 4;</code>
     */
    com.google.protobuf.ByteString
        getFortIdBytes();

    /**
     * <code>optional string fort_image_url = 5;</code>
     */
    java.lang.String getFortImageUrl();
    /**
     * <code>optional string fort_image_url = 5;</code>
     */
    com.google.protobuf.ByteString
        getFortImageUrlBytes();
  }
  /**
   * Protobuf type {@code com.github.aeonlucid.pogoprotos.map.pokemon.NearbyPokemon}
   */
  public  static final class NearbyPokemon extends
      com.google.protobuf.GeneratedMessageLite<
          NearbyPokemon, NearbyPokemon.Builder> implements
      // @@protoc_insertion_point(message_implements:com.github.aeonlucid.pogoprotos.map.pokemon.NearbyPokemon)
      NearbyPokemonOrBuilder {
    private NearbyPokemon() {
      fortId_ = "";
      fortImageUrl_ = "";
    }
    public static final int POKEMON_ID_FIELD_NUMBER = 1;
    private int pokemonId_;
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonId pokemon_id = 1;</code>
     */
    public int getPokemonIdValue() {
      return pokemonId_;
    }
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonId pokemon_id = 1;</code>
     */
    public com.github.aeonlucid.pogoprotos.Enums.PokemonId getPokemonId() {
      com.github.aeonlucid.pogoprotos.Enums.PokemonId result = com.github.aeonlucid.pogoprotos.Enums.PokemonId.forNumber(pokemonId_);
      return result == null ? com.github.aeonlucid.pogoprotos.Enums.PokemonId.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonId pokemon_id = 1;</code>
     */
    private void setPokemonIdValue(int value) {
        pokemonId_ = value;
    }
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonId pokemon_id = 1;</code>
     */
    private void setPokemonId(com.github.aeonlucid.pogoprotos.Enums.PokemonId value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      pokemonId_ = value.getNumber();
    }
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonId pokemon_id = 1;</code>
     */
    private void clearPokemonId() {
      
      pokemonId_ = 0;
    }

    public static final int DISTANCE_IN_METERS_FIELD_NUMBER = 2;
    private float distanceInMeters_;
    /**
     * <code>optional float distance_in_meters = 2;</code>
     */
    public float getDistanceInMeters() {
      return distanceInMeters_;
    }
    /**
     * <code>optional float distance_in_meters = 2;</code>
     */
    private void setDistanceInMeters(float value) {
      
      distanceInMeters_ = value;
    }
    /**
     * <code>optional float distance_in_meters = 2;</code>
     */
    private void clearDistanceInMeters() {
      
      distanceInMeters_ = 0F;
    }

    public static final int ENCOUNTER_ID_FIELD_NUMBER = 3;
    private long encounterId_;
    /**
     * <code>optional fixed64 encounter_id = 3;</code>
     */
    public long getEncounterId() {
      return encounterId_;
    }
    /**
     * <code>optional fixed64 encounter_id = 3;</code>
     */
    private void setEncounterId(long value) {
      
      encounterId_ = value;
    }
    /**
     * <code>optional fixed64 encounter_id = 3;</code>
     */
    private void clearEncounterId() {
      
      encounterId_ = 0L;
    }

    public static final int FORT_ID_FIELD_NUMBER = 4;
    private java.lang.String fortId_;
    /**
     * <code>optional string fort_id = 4;</code>
     */
    public java.lang.String getFortId() {
      return fortId_;
    }
    /**
     * <code>optional string fort_id = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFortIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(fortId_);
    }
    /**
     * <code>optional string fort_id = 4;</code>
     */
    private void setFortId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fortId_ = value;
    }
    /**
     * <code>optional string fort_id = 4;</code>
     */
    private void clearFortId() {
      
      fortId_ = getDefaultInstance().getFortId();
    }
    /**
     * <code>optional string fort_id = 4;</code>
     */
    private void setFortIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fortId_ = value.toStringUtf8();
    }

    public static final int FORT_IMAGE_URL_FIELD_NUMBER = 5;
    private java.lang.String fortImageUrl_;
    /**
     * <code>optional string fort_image_url = 5;</code>
     */
    public java.lang.String getFortImageUrl() {
      return fortImageUrl_;
    }
    /**
     * <code>optional string fort_image_url = 5;</code>
     */
    public com.google.protobuf.ByteString
        getFortImageUrlBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(fortImageUrl_);
    }
    /**
     * <code>optional string fort_image_url = 5;</code>
     */
    private void setFortImageUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fortImageUrl_ = value;
    }
    /**
     * <code>optional string fort_image_url = 5;</code>
     */
    private void clearFortImageUrl() {
      
      fortImageUrl_ = getDefaultInstance().getFortImageUrl();
    }
    /**
     * <code>optional string fort_image_url = 5;</code>
     */
    private void setFortImageUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fortImageUrl_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pokemonId_ != com.github.aeonlucid.pogoprotos.Enums.PokemonId.MISSINGNO.getNumber()) {
        output.writeEnum(1, pokemonId_);
      }
      if (distanceInMeters_ != 0F) {
        output.writeFloat(2, distanceInMeters_);
      }
      if (encounterId_ != 0L) {
        output.writeFixed64(3, encounterId_);
      }
      if (!fortId_.isEmpty()) {
        output.writeString(4, getFortId());
      }
      if (!fortImageUrl_.isEmpty()) {
        output.writeString(5, getFortImageUrl());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (pokemonId_ != com.github.aeonlucid.pogoprotos.Enums.PokemonId.MISSINGNO.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, pokemonId_);
      }
      if (distanceInMeters_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, distanceInMeters_);
      }
      if (encounterId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(3, encounterId_);
      }
      if (!fortId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getFortId());
      }
      if (!fortImageUrl_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getFortImageUrl());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.github.aeonlucid.pogoprotos.map.Pokemon.NearbyPokemon parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.aeonlucid.pogoprotos.map.Pokemon.NearbyPokemon parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.map.Pokemon.NearbyPokemon parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.aeonlucid.pogoprotos.map.Pokemon.NearbyPokemon parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.map.Pokemon.NearbyPokemon parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.map.Pokemon.NearbyPokemon parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.map.Pokemon.NearbyPokemon parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.map.Pokemon.NearbyPokemon parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.map.Pokemon.NearbyPokemon parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.map.Pokemon.NearbyPokemon parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.aeonlucid.pogoprotos.map.Pokemon.NearbyPokemon prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.github.aeonlucid.pogoprotos.map.pokemon.NearbyPokemon}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.github.aeonlucid.pogoprotos.map.Pokemon.NearbyPokemon, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.aeonlucid.pogoprotos.map.pokemon.NearbyPokemon)
        com.github.aeonlucid.pogoprotos.map.Pokemon.NearbyPokemonOrBuilder {
      // Construct using com.github.aeonlucid.pogoprotos.map.Pokemon.NearbyPokemon.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonId pokemon_id = 1;</code>
       */
      public int getPokemonIdValue() {
        return instance.getPokemonIdValue();
      }
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonId pokemon_id = 1;</code>
       */
      public Builder setPokemonIdValue(int value) {
        copyOnWrite();
        instance.setPokemonIdValue(value);
        return this;
      }
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonId pokemon_id = 1;</code>
       */
      public com.github.aeonlucid.pogoprotos.Enums.PokemonId getPokemonId() {
        return instance.getPokemonId();
      }
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonId pokemon_id = 1;</code>
       */
      public Builder setPokemonId(com.github.aeonlucid.pogoprotos.Enums.PokemonId value) {
        copyOnWrite();
        instance.setPokemonId(value);
        return this;
      }
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonId pokemon_id = 1;</code>
       */
      public Builder clearPokemonId() {
        copyOnWrite();
        instance.clearPokemonId();
        return this;
      }

      /**
       * <code>optional float distance_in_meters = 2;</code>
       */
      public float getDistanceInMeters() {
        return instance.getDistanceInMeters();
      }
      /**
       * <code>optional float distance_in_meters = 2;</code>
       */
      public Builder setDistanceInMeters(float value) {
        copyOnWrite();
        instance.setDistanceInMeters(value);
        return this;
      }
      /**
       * <code>optional float distance_in_meters = 2;</code>
       */
      public Builder clearDistanceInMeters() {
        copyOnWrite();
        instance.clearDistanceInMeters();
        return this;
      }

      /**
       * <code>optional fixed64 encounter_id = 3;</code>
       */
      public long getEncounterId() {
        return instance.getEncounterId();
      }
      /**
       * <code>optional fixed64 encounter_id = 3;</code>
       */
      public Builder setEncounterId(long value) {
        copyOnWrite();
        instance.setEncounterId(value);
        return this;
      }
      /**
       * <code>optional fixed64 encounter_id = 3;</code>
       */
      public Builder clearEncounterId() {
        copyOnWrite();
        instance.clearEncounterId();
        return this;
      }

      /**
       * <code>optional string fort_id = 4;</code>
       */
      public java.lang.String getFortId() {
        return instance.getFortId();
      }
      /**
       * <code>optional string fort_id = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFortIdBytes() {
        return instance.getFortIdBytes();
      }
      /**
       * <code>optional string fort_id = 4;</code>
       */
      public Builder setFortId(
          java.lang.String value) {
        copyOnWrite();
        instance.setFortId(value);
        return this;
      }
      /**
       * <code>optional string fort_id = 4;</code>
       */
      public Builder clearFortId() {
        copyOnWrite();
        instance.clearFortId();
        return this;
      }
      /**
       * <code>optional string fort_id = 4;</code>
       */
      public Builder setFortIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFortIdBytes(value);
        return this;
      }

      /**
       * <code>optional string fort_image_url = 5;</code>
       */
      public java.lang.String getFortImageUrl() {
        return instance.getFortImageUrl();
      }
      /**
       * <code>optional string fort_image_url = 5;</code>
       */
      public com.google.protobuf.ByteString
          getFortImageUrlBytes() {
        return instance.getFortImageUrlBytes();
      }
      /**
       * <code>optional string fort_image_url = 5;</code>
       */
      public Builder setFortImageUrl(
          java.lang.String value) {
        copyOnWrite();
        instance.setFortImageUrl(value);
        return this;
      }
      /**
       * <code>optional string fort_image_url = 5;</code>
       */
      public Builder clearFortImageUrl() {
        copyOnWrite();
        instance.clearFortImageUrl();
        return this;
      }
      /**
       * <code>optional string fort_image_url = 5;</code>
       */
      public Builder setFortImageUrlBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFortImageUrlBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.github.aeonlucid.pogoprotos.map.pokemon.NearbyPokemon)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.github.aeonlucid.pogoprotos.map.Pokemon.NearbyPokemon();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.github.aeonlucid.pogoprotos.map.Pokemon.NearbyPokemon other = (com.github.aeonlucid.pogoprotos.map.Pokemon.NearbyPokemon) arg1;
          pokemonId_ = visitor.visitInt(pokemonId_ != 0, pokemonId_,    other.pokemonId_ != 0, other.pokemonId_);
          distanceInMeters_ = visitor.visitFloat(distanceInMeters_ != 0F, distanceInMeters_,
              other.distanceInMeters_ != 0F, other.distanceInMeters_);
          encounterId_ = visitor.visitLong(encounterId_ != 0L, encounterId_,
              other.encounterId_ != 0L, other.encounterId_);
          fortId_ = visitor.visitString(!fortId_.isEmpty(), fortId_,
              !other.fortId_.isEmpty(), other.fortId_);
          fortImageUrl_ = visitor.visitString(!fortImageUrl_.isEmpty(), fortImageUrl_,
              !other.fortImageUrl_.isEmpty(), other.fortImageUrl_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  int rawValue = input.readEnum();

                  pokemonId_ = rawValue;
                  break;
                }
                case 21: {

                  distanceInMeters_ = input.readFloat();
                  break;
                }
                case 25: {

                  encounterId_ = input.readFixed64();
                  break;
                }
                case 34: {
                  String s = input.readStringRequireUtf8();

                  fortId_ = s;
                  break;
                }
                case 42: {
                  String s = input.readStringRequireUtf8();

                  fortImageUrl_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.github.aeonlucid.pogoprotos.map.Pokemon.NearbyPokemon.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.github.aeonlucid.pogoprotos.map.pokemon.NearbyPokemon)
    private static final com.github.aeonlucid.pogoprotos.map.Pokemon.NearbyPokemon DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NearbyPokemon();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.github.aeonlucid.pogoprotos.map.Pokemon.NearbyPokemon getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<NearbyPokemon> PARSER;

    public static com.google.protobuf.Parser<NearbyPokemon> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface MapPokemonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.aeonlucid.pogoprotos.map.pokemon.MapPokemon)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string spawn_point_id = 1;</code>
     */
    java.lang.String getSpawnPointId();
    /**
     * <code>optional string spawn_point_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getSpawnPointIdBytes();

    /**
     * <code>optional fixed64 encounter_id = 2;</code>
     */
    long getEncounterId();

    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonId pokemon_id = 3;</code>
     */
    int getPokemonIdValue();
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonId pokemon_id = 3;</code>
     */
    com.github.aeonlucid.pogoprotos.Enums.PokemonId getPokemonId();

    /**
     * <pre>
     * After this timestamp, the pokemon will be gone.
     * </pre>
     *
     * <code>optional int64 expiration_timestamp_ms = 4;</code>
     */
    long getExpirationTimestampMs();

    /**
     * <code>optional double latitude = 5;</code>
     */
    double getLatitude();

    /**
     * <code>optional double longitude = 6;</code>
     */
    double getLongitude();
  }
  /**
   * Protobuf type {@code com.github.aeonlucid.pogoprotos.map.pokemon.MapPokemon}
   */
  public  static final class MapPokemon extends
      com.google.protobuf.GeneratedMessageLite<
          MapPokemon, MapPokemon.Builder> implements
      // @@protoc_insertion_point(message_implements:com.github.aeonlucid.pogoprotos.map.pokemon.MapPokemon)
      MapPokemonOrBuilder {
    private MapPokemon() {
      spawnPointId_ = "";
    }
    public static final int SPAWN_POINT_ID_FIELD_NUMBER = 1;
    private java.lang.String spawnPointId_;
    /**
     * <code>optional string spawn_point_id = 1;</code>
     */
    public java.lang.String getSpawnPointId() {
      return spawnPointId_;
    }
    /**
     * <code>optional string spawn_point_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSpawnPointIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(spawnPointId_);
    }
    /**
     * <code>optional string spawn_point_id = 1;</code>
     */
    private void setSpawnPointId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      spawnPointId_ = value;
    }
    /**
     * <code>optional string spawn_point_id = 1;</code>
     */
    private void clearSpawnPointId() {
      
      spawnPointId_ = getDefaultInstance().getSpawnPointId();
    }
    /**
     * <code>optional string spawn_point_id = 1;</code>
     */
    private void setSpawnPointIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      spawnPointId_ = value.toStringUtf8();
    }

    public static final int ENCOUNTER_ID_FIELD_NUMBER = 2;
    private long encounterId_;
    /**
     * <code>optional fixed64 encounter_id = 2;</code>
     */
    public long getEncounterId() {
      return encounterId_;
    }
    /**
     * <code>optional fixed64 encounter_id = 2;</code>
     */
    private void setEncounterId(long value) {
      
      encounterId_ = value;
    }
    /**
     * <code>optional fixed64 encounter_id = 2;</code>
     */
    private void clearEncounterId() {
      
      encounterId_ = 0L;
    }

    public static final int POKEMON_ID_FIELD_NUMBER = 3;
    private int pokemonId_;
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonId pokemon_id = 3;</code>
     */
    public int getPokemonIdValue() {
      return pokemonId_;
    }
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonId pokemon_id = 3;</code>
     */
    public com.github.aeonlucid.pogoprotos.Enums.PokemonId getPokemonId() {
      com.github.aeonlucid.pogoprotos.Enums.PokemonId result = com.github.aeonlucid.pogoprotos.Enums.PokemonId.forNumber(pokemonId_);
      return result == null ? com.github.aeonlucid.pogoprotos.Enums.PokemonId.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonId pokemon_id = 3;</code>
     */
    private void setPokemonIdValue(int value) {
        pokemonId_ = value;
    }
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonId pokemon_id = 3;</code>
     */
    private void setPokemonId(com.github.aeonlucid.pogoprotos.Enums.PokemonId value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      pokemonId_ = value.getNumber();
    }
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonId pokemon_id = 3;</code>
     */
    private void clearPokemonId() {
      
      pokemonId_ = 0;
    }

    public static final int EXPIRATION_TIMESTAMP_MS_FIELD_NUMBER = 4;
    private long expirationTimestampMs_;
    /**
     * <pre>
     * After this timestamp, the pokemon will be gone.
     * </pre>
     *
     * <code>optional int64 expiration_timestamp_ms = 4;</code>
     */
    public long getExpirationTimestampMs() {
      return expirationTimestampMs_;
    }
    /**
     * <pre>
     * After this timestamp, the pokemon will be gone.
     * </pre>
     *
     * <code>optional int64 expiration_timestamp_ms = 4;</code>
     */
    private void setExpirationTimestampMs(long value) {
      
      expirationTimestampMs_ = value;
    }
    /**
     * <pre>
     * After this timestamp, the pokemon will be gone.
     * </pre>
     *
     * <code>optional int64 expiration_timestamp_ms = 4;</code>
     */
    private void clearExpirationTimestampMs() {
      
      expirationTimestampMs_ = 0L;
    }

    public static final int LATITUDE_FIELD_NUMBER = 5;
    private double latitude_;
    /**
     * <code>optional double latitude = 5;</code>
     */
    public double getLatitude() {
      return latitude_;
    }
    /**
     * <code>optional double latitude = 5;</code>
     */
    private void setLatitude(double value) {
      
      latitude_ = value;
    }
    /**
     * <code>optional double latitude = 5;</code>
     */
    private void clearLatitude() {
      
      latitude_ = 0D;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 6;
    private double longitude_;
    /**
     * <code>optional double longitude = 6;</code>
     */
    public double getLongitude() {
      return longitude_;
    }
    /**
     * <code>optional double longitude = 6;</code>
     */
    private void setLongitude(double value) {
      
      longitude_ = value;
    }
    /**
     * <code>optional double longitude = 6;</code>
     */
    private void clearLongitude() {
      
      longitude_ = 0D;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!spawnPointId_.isEmpty()) {
        output.writeString(1, getSpawnPointId());
      }
      if (encounterId_ != 0L) {
        output.writeFixed64(2, encounterId_);
      }
      if (pokemonId_ != com.github.aeonlucid.pogoprotos.Enums.PokemonId.MISSINGNO.getNumber()) {
        output.writeEnum(3, pokemonId_);
      }
      if (expirationTimestampMs_ != 0L) {
        output.writeInt64(4, expirationTimestampMs_);
      }
      if (latitude_ != 0D) {
        output.writeDouble(5, latitude_);
      }
      if (longitude_ != 0D) {
        output.writeDouble(6, longitude_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!spawnPointId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getSpawnPointId());
      }
      if (encounterId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(2, encounterId_);
      }
      if (pokemonId_ != com.github.aeonlucid.pogoprotos.Enums.PokemonId.MISSINGNO.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, pokemonId_);
      }
      if (expirationTimestampMs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, expirationTimestampMs_);
      }
      if (latitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, latitude_);
      }
      if (longitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, longitude_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.github.aeonlucid.pogoprotos.map.Pokemon.MapPokemon parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.aeonlucid.pogoprotos.map.Pokemon.MapPokemon parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.map.Pokemon.MapPokemon parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.aeonlucid.pogoprotos.map.Pokemon.MapPokemon parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.map.Pokemon.MapPokemon parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.map.Pokemon.MapPokemon parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.map.Pokemon.MapPokemon parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.map.Pokemon.MapPokemon parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.map.Pokemon.MapPokemon parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.map.Pokemon.MapPokemon parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.aeonlucid.pogoprotos.map.Pokemon.MapPokemon prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.github.aeonlucid.pogoprotos.map.pokemon.MapPokemon}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.github.aeonlucid.pogoprotos.map.Pokemon.MapPokemon, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.aeonlucid.pogoprotos.map.pokemon.MapPokemon)
        com.github.aeonlucid.pogoprotos.map.Pokemon.MapPokemonOrBuilder {
      // Construct using com.github.aeonlucid.pogoprotos.map.Pokemon.MapPokemon.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string spawn_point_id = 1;</code>
       */
      public java.lang.String getSpawnPointId() {
        return instance.getSpawnPointId();
      }
      /**
       * <code>optional string spawn_point_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSpawnPointIdBytes() {
        return instance.getSpawnPointIdBytes();
      }
      /**
       * <code>optional string spawn_point_id = 1;</code>
       */
      public Builder setSpawnPointId(
          java.lang.String value) {
        copyOnWrite();
        instance.setSpawnPointId(value);
        return this;
      }
      /**
       * <code>optional string spawn_point_id = 1;</code>
       */
      public Builder clearSpawnPointId() {
        copyOnWrite();
        instance.clearSpawnPointId();
        return this;
      }
      /**
       * <code>optional string spawn_point_id = 1;</code>
       */
      public Builder setSpawnPointIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSpawnPointIdBytes(value);
        return this;
      }

      /**
       * <code>optional fixed64 encounter_id = 2;</code>
       */
      public long getEncounterId() {
        return instance.getEncounterId();
      }
      /**
       * <code>optional fixed64 encounter_id = 2;</code>
       */
      public Builder setEncounterId(long value) {
        copyOnWrite();
        instance.setEncounterId(value);
        return this;
      }
      /**
       * <code>optional fixed64 encounter_id = 2;</code>
       */
      public Builder clearEncounterId() {
        copyOnWrite();
        instance.clearEncounterId();
        return this;
      }

      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonId pokemon_id = 3;</code>
       */
      public int getPokemonIdValue() {
        return instance.getPokemonIdValue();
      }
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonId pokemon_id = 3;</code>
       */
      public Builder setPokemonIdValue(int value) {
        copyOnWrite();
        instance.setPokemonIdValue(value);
        return this;
      }
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonId pokemon_id = 3;</code>
       */
      public com.github.aeonlucid.pogoprotos.Enums.PokemonId getPokemonId() {
        return instance.getPokemonId();
      }
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonId pokemon_id = 3;</code>
       */
      public Builder setPokemonId(com.github.aeonlucid.pogoprotos.Enums.PokemonId value) {
        copyOnWrite();
        instance.setPokemonId(value);
        return this;
      }
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.enums.PokemonId pokemon_id = 3;</code>
       */
      public Builder clearPokemonId() {
        copyOnWrite();
        instance.clearPokemonId();
        return this;
      }

      /**
       * <pre>
       * After this timestamp, the pokemon will be gone.
       * </pre>
       *
       * <code>optional int64 expiration_timestamp_ms = 4;</code>
       */
      public long getExpirationTimestampMs() {
        return instance.getExpirationTimestampMs();
      }
      /**
       * <pre>
       * After this timestamp, the pokemon will be gone.
       * </pre>
       *
       * <code>optional int64 expiration_timestamp_ms = 4;</code>
       */
      public Builder setExpirationTimestampMs(long value) {
        copyOnWrite();
        instance.setExpirationTimestampMs(value);
        return this;
      }
      /**
       * <pre>
       * After this timestamp, the pokemon will be gone.
       * </pre>
       *
       * <code>optional int64 expiration_timestamp_ms = 4;</code>
       */
      public Builder clearExpirationTimestampMs() {
        copyOnWrite();
        instance.clearExpirationTimestampMs();
        return this;
      }

      /**
       * <code>optional double latitude = 5;</code>
       */
      public double getLatitude() {
        return instance.getLatitude();
      }
      /**
       * <code>optional double latitude = 5;</code>
       */
      public Builder setLatitude(double value) {
        copyOnWrite();
        instance.setLatitude(value);
        return this;
      }
      /**
       * <code>optional double latitude = 5;</code>
       */
      public Builder clearLatitude() {
        copyOnWrite();
        instance.clearLatitude();
        return this;
      }

      /**
       * <code>optional double longitude = 6;</code>
       */
      public double getLongitude() {
        return instance.getLongitude();
      }
      /**
       * <code>optional double longitude = 6;</code>
       */
      public Builder setLongitude(double value) {
        copyOnWrite();
        instance.setLongitude(value);
        return this;
      }
      /**
       * <code>optional double longitude = 6;</code>
       */
      public Builder clearLongitude() {
        copyOnWrite();
        instance.clearLongitude();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.github.aeonlucid.pogoprotos.map.pokemon.MapPokemon)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.github.aeonlucid.pogoprotos.map.Pokemon.MapPokemon();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.github.aeonlucid.pogoprotos.map.Pokemon.MapPokemon other = (com.github.aeonlucid.pogoprotos.map.Pokemon.MapPokemon) arg1;
          spawnPointId_ = visitor.visitString(!spawnPointId_.isEmpty(), spawnPointId_,
              !other.spawnPointId_.isEmpty(), other.spawnPointId_);
          encounterId_ = visitor.visitLong(encounterId_ != 0L, encounterId_,
              other.encounterId_ != 0L, other.encounterId_);
          pokemonId_ = visitor.visitInt(pokemonId_ != 0, pokemonId_,    other.pokemonId_ != 0, other.pokemonId_);
          expirationTimestampMs_ = visitor.visitLong(expirationTimestampMs_ != 0L, expirationTimestampMs_,
              other.expirationTimestampMs_ != 0L, other.expirationTimestampMs_);
          latitude_ = visitor.visitDouble(latitude_ != 0D, latitude_,
              other.latitude_ != 0D, other.latitude_);
          longitude_ = visitor.visitDouble(longitude_ != 0D, longitude_,
              other.longitude_ != 0D, other.longitude_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  spawnPointId_ = s;
                  break;
                }
                case 17: {

                  encounterId_ = input.readFixed64();
                  break;
                }
                case 24: {
                  int rawValue = input.readEnum();

                  pokemonId_ = rawValue;
                  break;
                }
                case 32: {

                  expirationTimestampMs_ = input.readInt64();
                  break;
                }
                case 41: {

                  latitude_ = input.readDouble();
                  break;
                }
                case 49: {

                  longitude_ = input.readDouble();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.github.aeonlucid.pogoprotos.map.Pokemon.MapPokemon.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.github.aeonlucid.pogoprotos.map.pokemon.MapPokemon)
    private static final com.github.aeonlucid.pogoprotos.map.Pokemon.MapPokemon DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MapPokemon();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.github.aeonlucid.pogoprotos.map.Pokemon.MapPokemon getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<MapPokemon> PARSER;

    public static com.google.protobuf.Parser<MapPokemon> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface WildPokemonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.aeonlucid.pogoprotos.map.pokemon.WildPokemon)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional fixed64 encounter_id = 1;</code>
     */
    long getEncounterId();

    /**
     * <code>optional int64 last_modified_timestamp_ms = 2;</code>
     */
    long getLastModifiedTimestampMs();

    /**
     * <code>optional double latitude = 3;</code>
     */
    double getLatitude();

    /**
     * <code>optional double longitude = 4;</code>
     */
    double getLongitude();

    /**
     * <code>optional string spawn_point_id = 5;</code>
     */
    java.lang.String getSpawnPointId();
    /**
     * <code>optional string spawn_point_id = 5;</code>
     */
    com.google.protobuf.ByteString
        getSpawnPointIdBytes();

    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.data.PokemonData pokemon_data = 7;</code>
     */
    boolean hasPokemonData();
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.data.PokemonData pokemon_data = 7;</code>
     */
    com.github.aeonlucid.pogoprotos.Data.PokemonData getPokemonData();

    /**
     * <code>optional int32 time_till_hidden_ms = 11;</code>
     */
    int getTimeTillHiddenMs();
  }
  /**
   * Protobuf type {@code com.github.aeonlucid.pogoprotos.map.pokemon.WildPokemon}
   */
  public  static final class WildPokemon extends
      com.google.protobuf.GeneratedMessageLite<
          WildPokemon, WildPokemon.Builder> implements
      // @@protoc_insertion_point(message_implements:com.github.aeonlucid.pogoprotos.map.pokemon.WildPokemon)
      WildPokemonOrBuilder {
    private WildPokemon() {
      spawnPointId_ = "";
    }
    public static final int ENCOUNTER_ID_FIELD_NUMBER = 1;
    private long encounterId_;
    /**
     * <code>optional fixed64 encounter_id = 1;</code>
     */
    public long getEncounterId() {
      return encounterId_;
    }
    /**
     * <code>optional fixed64 encounter_id = 1;</code>
     */
    private void setEncounterId(long value) {
      
      encounterId_ = value;
    }
    /**
     * <code>optional fixed64 encounter_id = 1;</code>
     */
    private void clearEncounterId() {
      
      encounterId_ = 0L;
    }

    public static final int LAST_MODIFIED_TIMESTAMP_MS_FIELD_NUMBER = 2;
    private long lastModifiedTimestampMs_;
    /**
     * <code>optional int64 last_modified_timestamp_ms = 2;</code>
     */
    public long getLastModifiedTimestampMs() {
      return lastModifiedTimestampMs_;
    }
    /**
     * <code>optional int64 last_modified_timestamp_ms = 2;</code>
     */
    private void setLastModifiedTimestampMs(long value) {
      
      lastModifiedTimestampMs_ = value;
    }
    /**
     * <code>optional int64 last_modified_timestamp_ms = 2;</code>
     */
    private void clearLastModifiedTimestampMs() {
      
      lastModifiedTimestampMs_ = 0L;
    }

    public static final int LATITUDE_FIELD_NUMBER = 3;
    private double latitude_;
    /**
     * <code>optional double latitude = 3;</code>
     */
    public double getLatitude() {
      return latitude_;
    }
    /**
     * <code>optional double latitude = 3;</code>
     */
    private void setLatitude(double value) {
      
      latitude_ = value;
    }
    /**
     * <code>optional double latitude = 3;</code>
     */
    private void clearLatitude() {
      
      latitude_ = 0D;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 4;
    private double longitude_;
    /**
     * <code>optional double longitude = 4;</code>
     */
    public double getLongitude() {
      return longitude_;
    }
    /**
     * <code>optional double longitude = 4;</code>
     */
    private void setLongitude(double value) {
      
      longitude_ = value;
    }
    /**
     * <code>optional double longitude = 4;</code>
     */
    private void clearLongitude() {
      
      longitude_ = 0D;
    }

    public static final int SPAWN_POINT_ID_FIELD_NUMBER = 5;
    private java.lang.String spawnPointId_;
    /**
     * <code>optional string spawn_point_id = 5;</code>
     */
    public java.lang.String getSpawnPointId() {
      return spawnPointId_;
    }
    /**
     * <code>optional string spawn_point_id = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSpawnPointIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(spawnPointId_);
    }
    /**
     * <code>optional string spawn_point_id = 5;</code>
     */
    private void setSpawnPointId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      spawnPointId_ = value;
    }
    /**
     * <code>optional string spawn_point_id = 5;</code>
     */
    private void clearSpawnPointId() {
      
      spawnPointId_ = getDefaultInstance().getSpawnPointId();
    }
    /**
     * <code>optional string spawn_point_id = 5;</code>
     */
    private void setSpawnPointIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      spawnPointId_ = value.toStringUtf8();
    }

    public static final int POKEMON_DATA_FIELD_NUMBER = 7;
    private com.github.aeonlucid.pogoprotos.Data.PokemonData pokemonData_;
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.data.PokemonData pokemon_data = 7;</code>
     */
    public boolean hasPokemonData() {
      return pokemonData_ != null;
    }
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.data.PokemonData pokemon_data = 7;</code>
     */
    public com.github.aeonlucid.pogoprotos.Data.PokemonData getPokemonData() {
      return pokemonData_ == null ? com.github.aeonlucid.pogoprotos.Data.PokemonData.getDefaultInstance() : pokemonData_;
    }
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.data.PokemonData pokemon_data = 7;</code>
     */
    private void setPokemonData(com.github.aeonlucid.pogoprotos.Data.PokemonData value) {
      if (value == null) {
        throw new NullPointerException();
      }
      pokemonData_ = value;
      
      }
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.data.PokemonData pokemon_data = 7;</code>
     */
    private void setPokemonData(
        com.github.aeonlucid.pogoprotos.Data.PokemonData.Builder builderForValue) {
      pokemonData_ = builderForValue.build();
      
    }
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.data.PokemonData pokemon_data = 7;</code>
     */
    private void mergePokemonData(com.github.aeonlucid.pogoprotos.Data.PokemonData value) {
      if (pokemonData_ != null &&
          pokemonData_ != com.github.aeonlucid.pogoprotos.Data.PokemonData.getDefaultInstance()) {
        pokemonData_ =
          com.github.aeonlucid.pogoprotos.Data.PokemonData.newBuilder(pokemonData_).mergeFrom(value).buildPartial();
      } else {
        pokemonData_ = value;
      }
      
    }
    /**
     * <code>optional .com.github.aeonlucid.pogoprotos.data.PokemonData pokemon_data = 7;</code>
     */
    private void clearPokemonData() {  pokemonData_ = null;
      
    }

    public static final int TIME_TILL_HIDDEN_MS_FIELD_NUMBER = 11;
    private int timeTillHiddenMs_;
    /**
     * <code>optional int32 time_till_hidden_ms = 11;</code>
     */
    public int getTimeTillHiddenMs() {
      return timeTillHiddenMs_;
    }
    /**
     * <code>optional int32 time_till_hidden_ms = 11;</code>
     */
    private void setTimeTillHiddenMs(int value) {
      
      timeTillHiddenMs_ = value;
    }
    /**
     * <code>optional int32 time_till_hidden_ms = 11;</code>
     */
    private void clearTimeTillHiddenMs() {
      
      timeTillHiddenMs_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (encounterId_ != 0L) {
        output.writeFixed64(1, encounterId_);
      }
      if (lastModifiedTimestampMs_ != 0L) {
        output.writeInt64(2, lastModifiedTimestampMs_);
      }
      if (latitude_ != 0D) {
        output.writeDouble(3, latitude_);
      }
      if (longitude_ != 0D) {
        output.writeDouble(4, longitude_);
      }
      if (!spawnPointId_.isEmpty()) {
        output.writeString(5, getSpawnPointId());
      }
      if (pokemonData_ != null) {
        output.writeMessage(7, getPokemonData());
      }
      if (timeTillHiddenMs_ != 0) {
        output.writeInt32(11, timeTillHiddenMs_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (encounterId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(1, encounterId_);
      }
      if (lastModifiedTimestampMs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, lastModifiedTimestampMs_);
      }
      if (latitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, latitude_);
      }
      if (longitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, longitude_);
      }
      if (!spawnPointId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getSpawnPointId());
      }
      if (pokemonData_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getPokemonData());
      }
      if (timeTillHiddenMs_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, timeTillHiddenMs_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.github.aeonlucid.pogoprotos.map.Pokemon.WildPokemon parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.aeonlucid.pogoprotos.map.Pokemon.WildPokemon parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.map.Pokemon.WildPokemon parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.aeonlucid.pogoprotos.map.Pokemon.WildPokemon parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.map.Pokemon.WildPokemon parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.map.Pokemon.WildPokemon parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.map.Pokemon.WildPokemon parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.map.Pokemon.WildPokemon parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.map.Pokemon.WildPokemon parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.map.Pokemon.WildPokemon parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.aeonlucid.pogoprotos.map.Pokemon.WildPokemon prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.github.aeonlucid.pogoprotos.map.pokemon.WildPokemon}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.github.aeonlucid.pogoprotos.map.Pokemon.WildPokemon, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.aeonlucid.pogoprotos.map.pokemon.WildPokemon)
        com.github.aeonlucid.pogoprotos.map.Pokemon.WildPokemonOrBuilder {
      // Construct using com.github.aeonlucid.pogoprotos.map.Pokemon.WildPokemon.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional fixed64 encounter_id = 1;</code>
       */
      public long getEncounterId() {
        return instance.getEncounterId();
      }
      /**
       * <code>optional fixed64 encounter_id = 1;</code>
       */
      public Builder setEncounterId(long value) {
        copyOnWrite();
        instance.setEncounterId(value);
        return this;
      }
      /**
       * <code>optional fixed64 encounter_id = 1;</code>
       */
      public Builder clearEncounterId() {
        copyOnWrite();
        instance.clearEncounterId();
        return this;
      }

      /**
       * <code>optional int64 last_modified_timestamp_ms = 2;</code>
       */
      public long getLastModifiedTimestampMs() {
        return instance.getLastModifiedTimestampMs();
      }
      /**
       * <code>optional int64 last_modified_timestamp_ms = 2;</code>
       */
      public Builder setLastModifiedTimestampMs(long value) {
        copyOnWrite();
        instance.setLastModifiedTimestampMs(value);
        return this;
      }
      /**
       * <code>optional int64 last_modified_timestamp_ms = 2;</code>
       */
      public Builder clearLastModifiedTimestampMs() {
        copyOnWrite();
        instance.clearLastModifiedTimestampMs();
        return this;
      }

      /**
       * <code>optional double latitude = 3;</code>
       */
      public double getLatitude() {
        return instance.getLatitude();
      }
      /**
       * <code>optional double latitude = 3;</code>
       */
      public Builder setLatitude(double value) {
        copyOnWrite();
        instance.setLatitude(value);
        return this;
      }
      /**
       * <code>optional double latitude = 3;</code>
       */
      public Builder clearLatitude() {
        copyOnWrite();
        instance.clearLatitude();
        return this;
      }

      /**
       * <code>optional double longitude = 4;</code>
       */
      public double getLongitude() {
        return instance.getLongitude();
      }
      /**
       * <code>optional double longitude = 4;</code>
       */
      public Builder setLongitude(double value) {
        copyOnWrite();
        instance.setLongitude(value);
        return this;
      }
      /**
       * <code>optional double longitude = 4;</code>
       */
      public Builder clearLongitude() {
        copyOnWrite();
        instance.clearLongitude();
        return this;
      }

      /**
       * <code>optional string spawn_point_id = 5;</code>
       */
      public java.lang.String getSpawnPointId() {
        return instance.getSpawnPointId();
      }
      /**
       * <code>optional string spawn_point_id = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSpawnPointIdBytes() {
        return instance.getSpawnPointIdBytes();
      }
      /**
       * <code>optional string spawn_point_id = 5;</code>
       */
      public Builder setSpawnPointId(
          java.lang.String value) {
        copyOnWrite();
        instance.setSpawnPointId(value);
        return this;
      }
      /**
       * <code>optional string spawn_point_id = 5;</code>
       */
      public Builder clearSpawnPointId() {
        copyOnWrite();
        instance.clearSpawnPointId();
        return this;
      }
      /**
       * <code>optional string spawn_point_id = 5;</code>
       */
      public Builder setSpawnPointIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSpawnPointIdBytes(value);
        return this;
      }

      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.data.PokemonData pokemon_data = 7;</code>
       */
      public boolean hasPokemonData() {
        return instance.hasPokemonData();
      }
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.data.PokemonData pokemon_data = 7;</code>
       */
      public com.github.aeonlucid.pogoprotos.Data.PokemonData getPokemonData() {
        return instance.getPokemonData();
      }
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.data.PokemonData pokemon_data = 7;</code>
       */
      public Builder setPokemonData(com.github.aeonlucid.pogoprotos.Data.PokemonData value) {
        copyOnWrite();
        instance.setPokemonData(value);
        return this;
        }
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.data.PokemonData pokemon_data = 7;</code>
       */
      public Builder setPokemonData(
          com.github.aeonlucid.pogoprotos.Data.PokemonData.Builder builderForValue) {
        copyOnWrite();
        instance.setPokemonData(builderForValue);
        return this;
      }
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.data.PokemonData pokemon_data = 7;</code>
       */
      public Builder mergePokemonData(com.github.aeonlucid.pogoprotos.Data.PokemonData value) {
        copyOnWrite();
        instance.mergePokemonData(value);
        return this;
      }
      /**
       * <code>optional .com.github.aeonlucid.pogoprotos.data.PokemonData pokemon_data = 7;</code>
       */
      public Builder clearPokemonData() {  copyOnWrite();
        instance.clearPokemonData();
        return this;
      }

      /**
       * <code>optional int32 time_till_hidden_ms = 11;</code>
       */
      public int getTimeTillHiddenMs() {
        return instance.getTimeTillHiddenMs();
      }
      /**
       * <code>optional int32 time_till_hidden_ms = 11;</code>
       */
      public Builder setTimeTillHiddenMs(int value) {
        copyOnWrite();
        instance.setTimeTillHiddenMs(value);
        return this;
      }
      /**
       * <code>optional int32 time_till_hidden_ms = 11;</code>
       */
      public Builder clearTimeTillHiddenMs() {
        copyOnWrite();
        instance.clearTimeTillHiddenMs();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.github.aeonlucid.pogoprotos.map.pokemon.WildPokemon)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.github.aeonlucid.pogoprotos.map.Pokemon.WildPokemon();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.github.aeonlucid.pogoprotos.map.Pokemon.WildPokemon other = (com.github.aeonlucid.pogoprotos.map.Pokemon.WildPokemon) arg1;
          encounterId_ = visitor.visitLong(encounterId_ != 0L, encounterId_,
              other.encounterId_ != 0L, other.encounterId_);
          lastModifiedTimestampMs_ = visitor.visitLong(lastModifiedTimestampMs_ != 0L, lastModifiedTimestampMs_,
              other.lastModifiedTimestampMs_ != 0L, other.lastModifiedTimestampMs_);
          latitude_ = visitor.visitDouble(latitude_ != 0D, latitude_,
              other.latitude_ != 0D, other.latitude_);
          longitude_ = visitor.visitDouble(longitude_ != 0D, longitude_,
              other.longitude_ != 0D, other.longitude_);
          spawnPointId_ = visitor.visitString(!spawnPointId_.isEmpty(), spawnPointId_,
              !other.spawnPointId_.isEmpty(), other.spawnPointId_);
          pokemonData_ = visitor.visitMessage(pokemonData_, other.pokemonData_);
          timeTillHiddenMs_ = visitor.visitInt(timeTillHiddenMs_ != 0, timeTillHiddenMs_,
              other.timeTillHiddenMs_ != 0, other.timeTillHiddenMs_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 9: {

                  encounterId_ = input.readFixed64();
                  break;
                }
                case 16: {

                  lastModifiedTimestampMs_ = input.readInt64();
                  break;
                }
                case 25: {

                  latitude_ = input.readDouble();
                  break;
                }
                case 33: {

                  longitude_ = input.readDouble();
                  break;
                }
                case 42: {
                  String s = input.readStringRequireUtf8();

                  spawnPointId_ = s;
                  break;
                }
                case 58: {
                  com.github.aeonlucid.pogoprotos.Data.PokemonData.Builder subBuilder = null;
                  if (pokemonData_ != null) {
                    subBuilder = pokemonData_.toBuilder();
                  }
                  pokemonData_ = input.readMessage(com.github.aeonlucid.pogoprotos.Data.PokemonData.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(pokemonData_);
                    pokemonData_ = subBuilder.buildPartial();
                  }

                  break;
                }
                case 88: {

                  timeTillHiddenMs_ = input.readInt32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.github.aeonlucid.pogoprotos.map.Pokemon.WildPokemon.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.github.aeonlucid.pogoprotos.map.pokemon.WildPokemon)
    private static final com.github.aeonlucid.pogoprotos.map.Pokemon.WildPokemon DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new WildPokemon();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.github.aeonlucid.pogoprotos.map.Pokemon.WildPokemon getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<WildPokemon> PARSER;

    public static com.google.protobuf.Parser<WildPokemon> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
