// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/github/aeonlucid/pogoprotos/networking/platform/Requests.proto

package com.github.aeonlucid.pogoprotos.networking.platform;

public final class Requests {
  private Requests() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface BuyItemAndroidRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.aeonlucid.pogoprotos.networking.platform.requests.BuyItemAndroidRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * see https://developer.android.com/google/play/billing/billing_reference.html table 4
     * </pre>
     *
     * <code>optional string buy_item_intent = 1;</code>
     */
    java.lang.String getBuyItemIntent();
    /**
     * <pre>
     * see https://developer.android.com/google/play/billing/billing_reference.html table 4
     * </pre>
     *
     * <code>optional string buy_item_intent = 1;</code>
     */
    com.google.protobuf.ByteString
        getBuyItemIntentBytes();
  }
  /**
   * Protobuf type {@code com.github.aeonlucid.pogoprotos.networking.platform.requests.BuyItemAndroidRequest}
   */
  public  static final class BuyItemAndroidRequest extends
      com.google.protobuf.GeneratedMessageLite<
          BuyItemAndroidRequest, BuyItemAndroidRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:com.github.aeonlucid.pogoprotos.networking.platform.requests.BuyItemAndroidRequest)
      BuyItemAndroidRequestOrBuilder {
    private BuyItemAndroidRequest() {
      buyItemIntent_ = "";
    }
    public static final int BUY_ITEM_INTENT_FIELD_NUMBER = 1;
    private java.lang.String buyItemIntent_;
    /**
     * <pre>
     * see https://developer.android.com/google/play/billing/billing_reference.html table 4
     * </pre>
     *
     * <code>optional string buy_item_intent = 1;</code>
     */
    public java.lang.String getBuyItemIntent() {
      return buyItemIntent_;
    }
    /**
     * <pre>
     * see https://developer.android.com/google/play/billing/billing_reference.html table 4
     * </pre>
     *
     * <code>optional string buy_item_intent = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBuyItemIntentBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(buyItemIntent_);
    }
    /**
     * <pre>
     * see https://developer.android.com/google/play/billing/billing_reference.html table 4
     * </pre>
     *
     * <code>optional string buy_item_intent = 1;</code>
     */
    private void setBuyItemIntent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      buyItemIntent_ = value;
    }
    /**
     * <pre>
     * see https://developer.android.com/google/play/billing/billing_reference.html table 4
     * </pre>
     *
     * <code>optional string buy_item_intent = 1;</code>
     */
    private void clearBuyItemIntent() {
      
      buyItemIntent_ = getDefaultInstance().getBuyItemIntent();
    }
    /**
     * <pre>
     * see https://developer.android.com/google/play/billing/billing_reference.html table 4
     * </pre>
     *
     * <code>optional string buy_item_intent = 1;</code>
     */
    private void setBuyItemIntentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      buyItemIntent_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!buyItemIntent_.isEmpty()) {
        output.writeString(1, getBuyItemIntent());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!buyItemIntent_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getBuyItemIntent());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.github.aeonlucid.pogoprotos.networking.platform.requests.BuyItemAndroidRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.aeonlucid.pogoprotos.networking.platform.requests.BuyItemAndroidRequest)
        com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequestOrBuilder {
      // Construct using com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * see https://developer.android.com/google/play/billing/billing_reference.html table 4
       * </pre>
       *
       * <code>optional string buy_item_intent = 1;</code>
       */
      public java.lang.String getBuyItemIntent() {
        return instance.getBuyItemIntent();
      }
      /**
       * <pre>
       * see https://developer.android.com/google/play/billing/billing_reference.html table 4
       * </pre>
       *
       * <code>optional string buy_item_intent = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBuyItemIntentBytes() {
        return instance.getBuyItemIntentBytes();
      }
      /**
       * <pre>
       * see https://developer.android.com/google/play/billing/billing_reference.html table 4
       * </pre>
       *
       * <code>optional string buy_item_intent = 1;</code>
       */
      public Builder setBuyItemIntent(
          java.lang.String value) {
        copyOnWrite();
        instance.setBuyItemIntent(value);
        return this;
      }
      /**
       * <pre>
       * see https://developer.android.com/google/play/billing/billing_reference.html table 4
       * </pre>
       *
       * <code>optional string buy_item_intent = 1;</code>
       */
      public Builder clearBuyItemIntent() {
        copyOnWrite();
        instance.clearBuyItemIntent();
        return this;
      }
      /**
       * <pre>
       * see https://developer.android.com/google/play/billing/billing_reference.html table 4
       * </pre>
       *
       * <code>optional string buy_item_intent = 1;</code>
       */
      public Builder setBuyItemIntentBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setBuyItemIntentBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.github.aeonlucid.pogoprotos.networking.platform.requests.BuyItemAndroidRequest)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest other = (com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest) arg1;
          buyItemIntent_ = visitor.visitString(!buyItemIntent_.isEmpty(), buyItemIntent_,
              !other.buyItemIntent_.isEmpty(), other.buyItemIntent_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  buyItemIntent_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.github.aeonlucid.pogoprotos.networking.platform.requests.BuyItemAndroidRequest)
    private static final com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BuyItemAndroidRequest();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<BuyItemAndroidRequest> PARSER;

    public static com.google.protobuf.Parser<BuyItemAndroidRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SendEncryptedSignatureRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.aeonlucid.pogoprotos.networking.platform.requests.SendEncryptedSignatureRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional bytes encrypted_signature = 1;</code>
     */
    com.google.protobuf.ByteString getEncryptedSignature();
  }
  /**
   * Protobuf type {@code com.github.aeonlucid.pogoprotos.networking.platform.requests.SendEncryptedSignatureRequest}
   */
  public  static final class SendEncryptedSignatureRequest extends
      com.google.protobuf.GeneratedMessageLite<
          SendEncryptedSignatureRequest, SendEncryptedSignatureRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:com.github.aeonlucid.pogoprotos.networking.platform.requests.SendEncryptedSignatureRequest)
      SendEncryptedSignatureRequestOrBuilder {
    private SendEncryptedSignatureRequest() {
      encryptedSignature_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int ENCRYPTED_SIGNATURE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString encryptedSignature_;
    /**
     * <code>optional bytes encrypted_signature = 1;</code>
     */
    public com.google.protobuf.ByteString getEncryptedSignature() {
      return encryptedSignature_;
    }
    /**
     * <code>optional bytes encrypted_signature = 1;</code>
     */
    private void setEncryptedSignature(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      encryptedSignature_ = value;
    }
    /**
     * <code>optional bytes encrypted_signature = 1;</code>
     */
    private void clearEncryptedSignature() {
      
      encryptedSignature_ = getDefaultInstance().getEncryptedSignature();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!encryptedSignature_.isEmpty()) {
        output.writeBytes(1, encryptedSignature_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!encryptedSignature_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, encryptedSignature_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.github.aeonlucid.pogoprotos.networking.platform.requests.SendEncryptedSignatureRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.aeonlucid.pogoprotos.networking.platform.requests.SendEncryptedSignatureRequest)
        com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequestOrBuilder {
      // Construct using com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional bytes encrypted_signature = 1;</code>
       */
      public com.google.protobuf.ByteString getEncryptedSignature() {
        return instance.getEncryptedSignature();
      }
      /**
       * <code>optional bytes encrypted_signature = 1;</code>
       */
      public Builder setEncryptedSignature(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEncryptedSignature(value);
        return this;
      }
      /**
       * <code>optional bytes encrypted_signature = 1;</code>
       */
      public Builder clearEncryptedSignature() {
        copyOnWrite();
        instance.clearEncryptedSignature();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.github.aeonlucid.pogoprotos.networking.platform.requests.SendEncryptedSignatureRequest)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest other = (com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest) arg1;
          encryptedSignature_ = visitor.visitByteString(encryptedSignature_ != com.google.protobuf.ByteString.EMPTY, encryptedSignature_,
              other.encryptedSignature_ != com.google.protobuf.ByteString.EMPTY, other.encryptedSignature_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {

                  encryptedSignature_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.github.aeonlucid.pogoprotos.networking.platform.requests.SendEncryptedSignatureRequest)
    private static final com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SendEncryptedSignatureRequest();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SendEncryptedSignatureRequest> PARSER;

    public static com.google.protobuf.Parser<SendEncryptedSignatureRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface BuyItemPokeCoinsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.aeonlucid.pogoprotos.networking.platform.requests.BuyItemPokeCoinsRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string item_id = 1;</code>
     */
    java.lang.String getItemId();
    /**
     * <code>optional string item_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getItemIdBytes();
  }
  /**
   * Protobuf type {@code com.github.aeonlucid.pogoprotos.networking.platform.requests.BuyItemPokeCoinsRequest}
   */
  public  static final class BuyItemPokeCoinsRequest extends
      com.google.protobuf.GeneratedMessageLite<
          BuyItemPokeCoinsRequest, BuyItemPokeCoinsRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:com.github.aeonlucid.pogoprotos.networking.platform.requests.BuyItemPokeCoinsRequest)
      BuyItemPokeCoinsRequestOrBuilder {
    private BuyItemPokeCoinsRequest() {
      itemId_ = "";
    }
    public static final int ITEM_ID_FIELD_NUMBER = 1;
    private java.lang.String itemId_;
    /**
     * <code>optional string item_id = 1;</code>
     */
    public java.lang.String getItemId() {
      return itemId_;
    }
    /**
     * <code>optional string item_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getItemIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(itemId_);
    }
    /**
     * <code>optional string item_id = 1;</code>
     */
    private void setItemId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      itemId_ = value;
    }
    /**
     * <code>optional string item_id = 1;</code>
     */
    private void clearItemId() {
      
      itemId_ = getDefaultInstance().getItemId();
    }
    /**
     * <code>optional string item_id = 1;</code>
     */
    private void setItemIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      itemId_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!itemId_.isEmpty()) {
        output.writeString(1, getItemId());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!itemId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getItemId());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.github.aeonlucid.pogoprotos.networking.platform.requests.BuyItemPokeCoinsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.aeonlucid.pogoprotos.networking.platform.requests.BuyItemPokeCoinsRequest)
        com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequestOrBuilder {
      // Construct using com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string item_id = 1;</code>
       */
      public java.lang.String getItemId() {
        return instance.getItemId();
      }
      /**
       * <code>optional string item_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getItemIdBytes() {
        return instance.getItemIdBytes();
      }
      /**
       * <code>optional string item_id = 1;</code>
       */
      public Builder setItemId(
          java.lang.String value) {
        copyOnWrite();
        instance.setItemId(value);
        return this;
      }
      /**
       * <code>optional string item_id = 1;</code>
       */
      public Builder clearItemId() {
        copyOnWrite();
        instance.clearItemId();
        return this;
      }
      /**
       * <code>optional string item_id = 1;</code>
       */
      public Builder setItemIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setItemIdBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.github.aeonlucid.pogoprotos.networking.platform.requests.BuyItemPokeCoinsRequest)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest other = (com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest) arg1;
          itemId_ = visitor.visitString(!itemId_.isEmpty(), itemId_,
              !other.itemId_.isEmpty(), other.itemId_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  itemId_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.github.aeonlucid.pogoprotos.networking.platform.requests.BuyItemPokeCoinsRequest)
    private static final com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BuyItemPokeCoinsRequest();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<BuyItemPokeCoinsRequest> PARSER;

    public static com.google.protobuf.Parser<BuyItemPokeCoinsRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
